// Code generated by crtm-bundle; DO NOT EDIT.

package main

import (
	crtm "github.com/chainreactors/crtm/pkg"
)

var ToolSpec = crtm.BundleSpec{
	ID: "aiscan",
	Tools: map[string]string{
		"rg": "15.2.0",
	},
}
