// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: aop/event.proto

package aop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeltaOperation int32

const (
	DeltaOperation_DELTA_OPERATION_UNSPECIFIED DeltaOperation = 0
	DeltaOperation_DELTA_OPERATION_START       DeltaOperation = 1
	DeltaOperation_DELTA_OPERATION_APPEND      DeltaOperation = 2
	DeltaOperation_DELTA_OPERATION_REPLACE     DeltaOperation = 3
	DeltaOperation_DELTA_OPERATION_END         DeltaOperation = 4
)

// Enum value maps for DeltaOperation.
var (
	DeltaOperation_name = map[int32]string{
		0: "DELTA_OPERATION_UNSPECIFIED",
		1: "DELTA_OPERATION_START",
		2: "DELTA_OPERATION_APPEND",
		3: "DELTA_OPERATION_REPLACE",
		4: "DELTA_OPERATION_END",
	}
	DeltaOperation_value = map[string]int32{
		"DELTA_OPERATION_UNSPECIFIED": 0,
		"DELTA_OPERATION_START":       1,
		"DELTA_OPERATION_APPEND":      2,
		"DELTA_OPERATION_REPLACE":     3,
		"DELTA_OPERATION_END":         4,
	}
)

func (x DeltaOperation) Enum() *DeltaOperation {
	p := new(DeltaOperation)
	*p = x
	return p
}

func (x DeltaOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeltaOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_aop_event_proto_enumTypes[0].Descriptor()
}

func (DeltaOperation) Type() protoreflect.EnumType {
	return &file_aop_event_proto_enumTypes[0]
}

func (x DeltaOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeltaOperation.Descriptor instead.
func (DeltaOperation) EnumDescriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_REQUEST     Direction = 1
	Direction_DIRECTION_RESPONSE    Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_REQUEST",
		2: "DIRECTION_RESPONSE",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_REQUEST":     1,
		"DIRECTION_RESPONSE":    2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_aop_event_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_aop_event_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{1}
}

type SessionStarted struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ParentSessionId  string                 `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	ParentToolCallId string                 `protobuf:"bytes,3,opt,name=parent_tool_call_id,json=parentToolCallId,proto3" json:"parent_tool_call_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionStarted) Reset() {
	*x = SessionStarted{}
	mi := &file_aop_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStarted) ProtoMessage() {}

func (x *SessionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStarted.ProtoReflect.Descriptor instead.
func (*SessionStarted) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStarted) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionStarted) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *SessionStarted) GetParentToolCallId() string {
	if x != nil {
		return x.ParentToolCallId
	}
	return ""
}

type SessionEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnded) Reset() {
	*x = SessionEnded{}
	mi := &file_aop_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnded) ProtoMessage() {}

func (x *SessionEnded) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnded.ProtoReflect.Descriptor instead.
func (*SessionEnded) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{1}
}

func (x *SessionEnded) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TurnStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnStarted) Reset() {
	*x = TurnStarted{}
	mi := &file_aop_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnStarted) ProtoMessage() {}

func (x *TurnStarted) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnStarted.ProtoReflect.Descriptor instead.
func (*TurnStarted) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{2}
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_aop_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProtocolError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Detail        map[string]uint64      `protobuf:"bytes,5,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_aop_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUsage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TokenUsage) GetDetail() map[string]uint64 {
	if x != nil {
		return x.Detail
	}
	return nil
}

type TurnEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopReason    string                 `protobuf:"bytes,1,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	Error         *ProtocolError         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	ContextTokens uint64                 `protobuf:"varint,4,opt,name=context_tokens,json=contextTokens,proto3" json:"context_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnEnded) Reset() {
	*x = TurnEnded{}
	mi := &file_aop_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEnded) ProtoMessage() {}

func (x *TurnEnded) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnEnded.ProtoReflect.Descriptor instead.
func (*TurnEnded) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{5}
}

func (x *TurnEnded) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *TurnEnded) GetError() *ProtocolError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TurnEnded) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *TurnEnded) GetContextTokens() uint64 {
	if x != nil {
		return x.ContextTokens
	}
	return 0
}

type MessageDelta struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MessageId    string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ContentIndex uint32                 `protobuf:"varint,2,opt,name=content_index,json=contentIndex,proto3" json:"content_index,omitempty"`
	Operation    DeltaOperation         `protobuf:"varint,3,opt,name=operation,proto3,enum=aop.DeltaOperation" json:"operation,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MessageDelta_Text
	//	*MessageDelta_Reasoning
	//	*MessageDelta_Refusal
	//	*MessageDelta_Data
	//	*MessageDelta_ToolArguments
	//	*MessageDelta_Content
	Value         isMessageDelta_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDelta) Reset() {
	*x = MessageDelta{}
	mi := &file_aop_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelta) ProtoMessage() {}

func (x *MessageDelta) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelta.ProtoReflect.Descriptor instead.
func (*MessageDelta) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{6}
}

func (x *MessageDelta) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDelta) GetContentIndex() uint32 {
	if x != nil {
		return x.ContentIndex
	}
	return 0
}

func (x *MessageDelta) GetOperation() DeltaOperation {
	if x != nil {
		return x.Operation
	}
	return DeltaOperation_DELTA_OPERATION_UNSPECIFIED
}

func (x *MessageDelta) GetValue() isMessageDelta_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageDelta) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MessageDelta) GetReasoning() string {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_Reasoning); ok {
			return x.Reasoning
		}
	}
	return ""
}

func (x *MessageDelta) GetRefusal() string {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_Refusal); ok {
			return x.Refusal
		}
	}
	return ""
}

func (x *MessageDelta) GetData() []byte {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *MessageDelta) GetToolArguments() string {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_ToolArguments); ok {
			return x.ToolArguments
		}
	}
	return ""
}

func (x *MessageDelta) GetContent() *Content {
	if x != nil {
		if x, ok := x.Value.(*MessageDelta_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isMessageDelta_Value interface {
	isMessageDelta_Value()
}

type MessageDelta_Text struct {
	Text string `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type MessageDelta_Reasoning struct {
	Reasoning string `protobuf:"bytes,5,opt,name=reasoning,proto3,oneof"`
}

type MessageDelta_Refusal struct {
	Refusal string `protobuf:"bytes,6,opt,name=refusal,proto3,oneof"`
}

type MessageDelta_Data struct {
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type MessageDelta_ToolArguments struct {
	ToolArguments string `protobuf:"bytes,8,opt,name=tool_arguments,json=toolArguments,proto3,oneof"`
}

type MessageDelta_Content struct {
	Content *Content `protobuf:"bytes,9,opt,name=content,proto3,oneof"`
}

func (*MessageDelta_Text) isMessageDelta_Value() {}

func (*MessageDelta_Reasoning) isMessageDelta_Value() {}

func (*MessageDelta_Refusal) isMessageDelta_Value() {}

func (*MessageDelta_Data) isMessageDelta_Value() {}

func (*MessageDelta_ToolArguments) isMessageDelta_Value() {}

func (*MessageDelta_Content) isMessageDelta_Value() {}

type ToolCallDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_aop_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCallDelta) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallDelta) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallDelta) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_aop_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{8}
}

func (x *Status) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ProviderMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMetadata) Reset() {
	*x = ProviderMetadata{}
	mi := &file_aop_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMetadata) ProtoMessage() {}

func (x *ProviderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMetadata.ProtoReflect.Descriptor instead.
func (*ProviderMetadata) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderMetadata) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// ProviderFrame preserves one exact provider body or stream frame.
type ProviderFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=aop.Direction" json:"direction,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	MediaType     string                 `protobuf:"bytes,7,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Metadata      []*ProviderMetadata    `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderFrame) Reset() {
	*x = ProviderFrame{}
	mi := &file_aop_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderFrame) ProtoMessage() {}

func (x *ProviderFrame) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderFrame.ProtoReflect.Descriptor instead.
func (*ProviderFrame) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderFrame) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderFrame) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProviderFrame) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProviderFrame) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *ProviderFrame) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ProviderFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProviderFrame) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ProviderFrame) GetMetadata() []*ProviderMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmittedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	SessionId  string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TurnId     string                 `protobuf:"bytes,4,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Emitter    string                 `protobuf:"bytes,5,opt,name=emitter,proto3" json:"emitter,omitempty"`
	Seq        uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	Extensions []*anypb.Any           `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_SessionStarted
	//	*Event_SessionEnded
	//	*Event_TurnStarted
	//	*Event_TurnEnded
	//	*Event_Message
	//	*Event_MessageDelta
	//	*Event_ToolCall
	//	*Event_ToolCallDelta
	//	*Event_ToolResult
	//	*Event_Usage
	//	*Event_Error
	//	*Event_Status
	//	*Event_ProviderFrame
	//	*Event_Extension
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_aop_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_aop_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_aop_event_proto_rawDescGZIP(), []int{11}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Event) GetEmitter() string {
	if x != nil {
		return x.Emitter
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetExtensions() []*anypb.Any {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSessionStarted() *SessionStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_SessionStarted); ok {
			return x.SessionStarted
		}
	}
	return nil
}

func (x *Event) GetSessionEnded() *SessionEnded {
	if x != nil {
		if x, ok := x.Payload.(*Event_SessionEnded); ok {
			return x.SessionEnded
		}
	}
	return nil
}

func (x *Event) GetTurnStarted() *TurnStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_TurnStarted); ok {
			return x.TurnStarted
		}
	}
	return nil
}

func (x *Event) GetTurnEnded() *TurnEnded {
	if x != nil {
		if x, ok := x.Payload.(*Event_TurnEnded); ok {
			return x.TurnEnded
		}
	}
	return nil
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Event_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Event) GetMessageDelta() *MessageDelta {
	if x != nil {
		if x, ok := x.Payload.(*Event_MessageDelta); ok {
			return x.MessageDelta
		}
	}
	return nil
}

func (x *Event) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Event) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *Event) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *Event) GetUsage() *TokenUsage {
	if x != nil {
		if x, ok := x.Payload.(*Event_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *Event) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Payload.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Event) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Payload.(*Event_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Event) GetProviderFrame() *ProviderFrame {
	if x != nil {
		if x, ok := x.Payload.(*Event_ProviderFrame); ok {
			return x.ProviderFrame
		}
	}
	return nil
}

func (x *Event) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.Payload.(*Event_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_SessionStarted struct {
	SessionStarted *SessionStarted `protobuf:"bytes,10,opt,name=session_started,json=sessionStarted,proto3,oneof"`
}

type Event_SessionEnded struct {
	SessionEnded *SessionEnded `protobuf:"bytes,11,opt,name=session_ended,json=sessionEnded,proto3,oneof"`
}

type Event_TurnStarted struct {
	TurnStarted *TurnStarted `protobuf:"bytes,12,opt,name=turn_started,json=turnStarted,proto3,oneof"`
}

type Event_TurnEnded struct {
	TurnEnded *TurnEnded `protobuf:"bytes,13,opt,name=turn_ended,json=turnEnded,proto3,oneof"`
}

type Event_Message struct {
	Message *Message `protobuf:"bytes,14,opt,name=message,proto3,oneof"`
}

type Event_MessageDelta struct {
	MessageDelta *MessageDelta `protobuf:"bytes,15,opt,name=message_delta,json=messageDelta,proto3,oneof"`
}

type Event_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,16,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type Event_ToolCallDelta struct {
	ToolCallDelta *ToolCallDelta `protobuf:"bytes,17,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type Event_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,18,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type Event_Usage struct {
	Usage *TokenUsage `protobuf:"bytes,19,opt,name=usage,proto3,oneof"`
}

type Event_Error struct {
	Error *ProtocolError `protobuf:"bytes,20,opt,name=error,proto3,oneof"`
}

type Event_Status struct {
	Status *Status `protobuf:"bytes,21,opt,name=status,proto3,oneof"`
}

type Event_ProviderFrame struct {
	ProviderFrame *ProviderFrame `protobuf:"bytes,23,opt,name=provider_frame,json=providerFrame,proto3,oneof"`
}

type Event_Extension struct {
	Extension *anypb.Any `protobuf:"bytes,24,opt,name=extension,proto3,oneof"`
}

func (*Event_SessionStarted) isEvent_Payload() {}

func (*Event_SessionEnded) isEvent_Payload() {}

func (*Event_TurnStarted) isEvent_Payload() {}

func (*Event_TurnEnded) isEvent_Payload() {}

func (*Event_Message) isEvent_Payload() {}

func (*Event_MessageDelta) isEvent_Payload() {}

func (*Event_ToolCall) isEvent_Payload() {}

func (*Event_ToolCallDelta) isEvent_Payload() {}

func (*Event_ToolResult) isEvent_Payload() {}

func (*Event_Usage) isEvent_Payload() {}

func (*Event_Error) isEvent_Payload() {}

func (*Event_Status) isEvent_Payload() {}

func (*Event_ProviderFrame) isEvent_Payload() {}

func (*Event_Extension) isEvent_Payload() {}

var File_aop_event_proto protoreflect.FileDescriptor

const file_aop_event_proto_rawDesc = "" +
	"\n" +
	"\x0faop/event.proto\x12\x03aop\x1a\x11aop/content.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n" +
	"\x0eSessionStarted\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12*\n" +
	"\x11parent_session_id\x18\x02 \x01(\tR\x0fparentSessionId\x12-\n" +
	"\x13parent_tool_call_id\x18\x03 \x01(\tR\x10parentToolCallId\"&\n" +
	"\fSessionEnded\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\r\n" +
	"\vTurnStarted\"a\n" +
	"\rProtocolError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryableJ\x04\b\x04\x10\x05\"\xfd\x01\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x123\n" +
	"\x06detail\x18\x05 \x03(\v2\x1b.aop.TokenUsage.DetailEntryR\x06detail\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa4\x01\n" +
	"\tTurnEnded\x12\x1f\n" +
	"\vstop_reason\x18\x01 \x01(\tR\n" +
	"stopReason\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x12.aop.ProtocolErrorR\x05error\x12%\n" +
	"\x05usage\x18\x03 \x01(\v2\x0f.aop.TokenUsageR\x05usage\x12%\n" +
	"\x0econtext_tokens\x18\x04 \x01(\x04R\rcontextTokens\"\xc9\x02\n" +
	"\fMessageDelta\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12#\n" +
	"\rcontent_index\x18\x02 \x01(\rR\fcontentIndex\x121\n" +
	"\toperation\x18\x03 \x01(\x0e2\x13.aop.DeltaOperationR\toperation\x12\x14\n" +
	"\x04text\x18\x04 \x01(\tH\x00R\x04text\x12\x1e\n" +
	"\treasoning\x18\x05 \x01(\tH\x00R\treasoning\x12\x1a\n" +
	"\arefusal\x18\x06 \x01(\tH\x00R\arefusal\x12\x14\n" +
	"\x04data\x18\a \x01(\fH\x00R\x04data\x12'\n" +
	"\x0etool_arguments\x18\b \x01(\tH\x00R\rtoolArguments\x12(\n" +
	"\acontent\x18\t \x01(\v2\f.aop.ContentH\x00R\acontentB\a\n" +
	"\x05value\"p\n" +
	"\rToolCallDelta\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\fR\targuments\"$\n" +
	"\x06Status\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05stateJ\x04\b\x02\x10\x03\"<\n" +
	"\x10ProviderMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x9e\x02\n" +
	"\rProviderFrame\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12,\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x0e.aop.DirectionR\tdirection\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"media_type\x18\a \x01(\tR\tmediaType\x121\n" +
	"\bmetadata\x18\b \x03(\v2\x15.aop.ProviderMetadataR\bmetadata\"\xd8\a\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"emitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\aturn_id\x18\x04 \x01(\tR\x06turnId\x12\x18\n" +
	"\aemitter\x18\x05 \x01(\tR\aemitter\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x124\n" +
	"\n" +
	"extensions\x18\b \x03(\v2\x14.google.protobuf.AnyR\n" +
	"extensions\x12>\n" +
	"\x0fsession_started\x18\n" +
	" \x01(\v2\x13.aop.SessionStartedH\x00R\x0esessionStarted\x128\n" +
	"\rsession_ended\x18\v \x01(\v2\x11.aop.SessionEndedH\x00R\fsessionEnded\x125\n" +
	"\fturn_started\x18\f \x01(\v2\x10.aop.TurnStartedH\x00R\vturnStarted\x12/\n" +
	"\n" +
	"turn_ended\x18\r \x01(\v2\x0e.aop.TurnEndedH\x00R\tturnEnded\x12(\n" +
	"\amessage\x18\x0e \x01(\v2\f.aop.MessageH\x00R\amessage\x128\n" +
	"\rmessage_delta\x18\x0f \x01(\v2\x11.aop.MessageDeltaH\x00R\fmessageDelta\x12,\n" +
	"\ttool_call\x18\x10 \x01(\v2\r.aop.ToolCallH\x00R\btoolCall\x12<\n" +
	"\x0ftool_call_delta\x18\x11 \x01(\v2\x12.aop.ToolCallDeltaH\x00R\rtoolCallDelta\x122\n" +
	"\vtool_result\x18\x12 \x01(\v2\x0f.aop.ToolResultH\x00R\n" +
	"toolResult\x12'\n" +
	"\x05usage\x18\x13 \x01(\v2\x0f.aop.TokenUsageH\x00R\x05usage\x12*\n" +
	"\x05error\x18\x14 \x01(\v2\x12.aop.ProtocolErrorH\x00R\x05error\x12%\n" +
	"\x06status\x18\x15 \x01(\v2\v.aop.StatusH\x00R\x06status\x12;\n" +
	"\x0eprovider_frame\x18\x17 \x01(\v2\x12.aop.ProviderFrameH\x00R\rproviderFrame\x124\n" +
	"\textension\x18\x18 \x01(\v2\x14.google.protobuf.AnyH\x00R\textensionB\t\n" +
	"\apayloadJ\x04\b\a\x10\bJ\x04\b\x16\x10\x17*\x9e\x01\n" +
	"\x0eDeltaOperation\x12\x1f\n" +
	"\x1bDELTA_OPERATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DELTA_OPERATION_START\x10\x01\x12\x1a\n" +
	"\x16DELTA_OPERATION_APPEND\x10\x02\x12\x1b\n" +
	"\x17DELTA_OPERATION_REPLACE\x10\x03\x12\x17\n" +
	"\x13DELTA_OPERATION_END\x10\x04*U\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_REQUEST\x10\x01\x12\x16\n" +
	"\x12DIRECTION_RESPONSE\x10\x02B%Z#github.com/chainreactors/aiscan/aopb\x06proto3"

var (
	file_aop_event_proto_rawDescOnce sync.Once
	file_aop_event_proto_rawDescData []byte
)

func file_aop_event_proto_rawDescGZIP() []byte {
	file_aop_event_proto_rawDescOnce.Do(func() {
		file_aop_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aop_event_proto_rawDesc), len(file_aop_event_proto_rawDesc)))
	})
	return file_aop_event_proto_rawDescData
}

var file_aop_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aop_event_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_aop_event_proto_goTypes = []any{
	(DeltaOperation)(0),           // 0: aop.DeltaOperation
	(Direction)(0),                // 1: aop.Direction
	(*SessionStarted)(nil),        // 2: aop.SessionStarted
	(*SessionEnded)(nil),          // 3: aop.SessionEnded
	(*TurnStarted)(nil),           // 4: aop.TurnStarted
	(*ProtocolError)(nil),         // 5: aop.ProtocolError
	(*TokenUsage)(nil),            // 6: aop.TokenUsage
	(*TurnEnded)(nil),             // 7: aop.TurnEnded
	(*MessageDelta)(nil),          // 8: aop.MessageDelta
	(*ToolCallDelta)(nil),         // 9: aop.ToolCallDelta
	(*Status)(nil),                // 10: aop.Status
	(*ProviderMetadata)(nil),      // 11: aop.ProviderMetadata
	(*ProviderFrame)(nil),         // 12: aop.ProviderFrame
	(*Event)(nil),                 // 13: aop.Event
	nil,                           // 14: aop.TokenUsage.DetailEntry
	(*Content)(nil),               // 15: aop.Content
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 17: google.protobuf.Any
	(*Message)(nil),               // 18: aop.Message
	(*ToolCall)(nil),              // 19: aop.ToolCall
	(*ToolResult)(nil),            // 20: aop.ToolResult
}
var file_aop_event_proto_depIdxs = []int32{
	14, // 0: aop.TokenUsage.detail:type_name -> aop.TokenUsage.DetailEntry
	5,  // 1: aop.TurnEnded.error:type_name -> aop.ProtocolError
	6,  // 2: aop.TurnEnded.usage:type_name -> aop.TokenUsage
	0,  // 3: aop.MessageDelta.operation:type_name -> aop.DeltaOperation
	15, // 4: aop.MessageDelta.content:type_name -> aop.Content
	1,  // 5: aop.ProviderFrame.direction:type_name -> aop.Direction
	11, // 6: aop.ProviderFrame.metadata:type_name -> aop.ProviderMetadata
	16, // 7: aop.Event.emitted_at:type_name -> google.protobuf.Timestamp
	17, // 8: aop.Event.extensions:type_name -> google.protobuf.Any
	2,  // 9: aop.Event.session_started:type_name -> aop.SessionStarted
	3,  // 10: aop.Event.session_ended:type_name -> aop.SessionEnded
	4,  // 11: aop.Event.turn_started:type_name -> aop.TurnStarted
	7,  // 12: aop.Event.turn_ended:type_name -> aop.TurnEnded
	18, // 13: aop.Event.message:type_name -> aop.Message
	8,  // 14: aop.Event.message_delta:type_name -> aop.MessageDelta
	19, // 15: aop.Event.tool_call:type_name -> aop.ToolCall
	9,  // 16: aop.Event.tool_call_delta:type_name -> aop.ToolCallDelta
	20, // 17: aop.Event.tool_result:type_name -> aop.ToolResult
	6,  // 18: aop.Event.usage:type_name -> aop.TokenUsage
	5,  // 19: aop.Event.error:type_name -> aop.ProtocolError
	10, // 20: aop.Event.status:type_name -> aop.Status
	12, // 21: aop.Event.provider_frame:type_name -> aop.ProviderFrame
	17, // 22: aop.Event.extension:type_name -> google.protobuf.Any
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_aop_event_proto_init() }
func file_aop_event_proto_init() {
	if File_aop_event_proto != nil {
		return
	}
	file_aop_content_proto_init()
	file_aop_event_proto_msgTypes[6].OneofWrappers = []any{
		(*MessageDelta_Text)(nil),
		(*MessageDelta_Reasoning)(nil),
		(*MessageDelta_Refusal)(nil),
		(*MessageDelta_Data)(nil),
		(*MessageDelta_ToolArguments)(nil),
		(*MessageDelta_Content)(nil),
	}
	file_aop_event_proto_msgTypes[11].OneofWrappers = []any{
		(*Event_SessionStarted)(nil),
		(*Event_SessionEnded)(nil),
		(*Event_TurnStarted)(nil),
		(*Event_TurnEnded)(nil),
		(*Event_Message)(nil),
		(*Event_MessageDelta)(nil),
		(*Event_ToolCall)(nil),
		(*Event_ToolCallDelta)(nil),
		(*Event_ToolResult)(nil),
		(*Event_Usage)(nil),
		(*Event_Error)(nil),
		(*Event_Status)(nil),
		(*Event_ProviderFrame)(nil),
		(*Event_Extension)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aop_event_proto_rawDesc), len(file_aop_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aop_event_proto_goTypes,
		DependencyIndexes: file_aop_event_proto_depIdxs,
		EnumInfos:         file_aop_event_proto_enumTypes,
		MessageInfos:      file_aop_event_proto_msgTypes,
	}.Build()
	File_aop_event_proto = out.File
	file_aop_event_proto_goTypes = nil
	file_aop_event_proto_depIdxs = nil
}
