package curl

import (
	"bufio"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// seedCookies loads cookies into the jar before the request. Following curl, a
// value containing '=' is an inline cookie string; anything else is a file
// (Netscape format, or plain name=value lines).
func seedCookies(jar http.CookieJar, target *url.URL, spec, workDir string) error {
	if jar == nil {
		return nil
	}
	if strings.Contains(spec, "=") {
		jar.SetCookies(target, parseCookieString(spec))
		return nil
	}
	file, err := os.Open(resolvePath(workDir, spec))
	if err != nil {
		return fmt.Errorf("curl: (25) cannot open cookie file %q: %w", spec, err)
	}
	defer file.Close()

	var inline []*http.Cookie
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || (strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "#HttpOnly_")) {
			continue
		}
		line = strings.TrimPrefix(line, "#HttpOnly_")
		if fields := strings.Split(line, "\t"); len(fields) == 7 {
			// domain, flag, path, secure, expiration, name, value
			jar.SetCookies(cookieURL(fields[0], fields[2], target), []*http.Cookie{newCookie(fields[5], fields[6])})
			continue
		}
		inline = append(inline, parseCookieString(line)...)
	}
	if len(inline) > 0 {
		jar.SetCookies(target, inline)
	}
	return scanner.Err()
}

func parseCookieString(spec string) []*http.Cookie {
	var cookies []*http.Cookie
	for _, pair := range strings.Split(spec, ";") {
		name, value, ok := strings.Cut(strings.TrimSpace(pair), "=")
		if !ok || name == "" {
			continue
		}
		cookies = append(cookies, newCookie(strings.TrimSpace(name), strings.TrimSpace(value)))
	}
	return cookies
}

func newCookie(name, value string) *http.Cookie {
	// Cookie flags are supplied by the caller's cookie source. This tool is a
	// client-side jar, so it must not invent Secure/HttpOnly/SameSite policy.
	return &http.Cookie{Name: name, Value: value} //nolint:gosec // G124: preserve source cookie attributes
}

func cookieURL(domain, path string, fallback *url.URL) *url.URL {
	domain = strings.TrimPrefix(domain, ".")
	if domain == "" {
		return fallback
	}
	if path == "" {
		path = "/"
	}
	return &url.URL{Scheme: "https", Host: domain, Path: path}
}

// writeCookieJar persists the jar's cookies for the final URL in Netscape
// format, the shape curl's -c produces and -b consumes. http.CookieJar exposes
// only name/value, so domain/path are taken from the request URL.
func writeCookieJar(jar http.CookieJar, u *url.URL, path string) error {
	if jar == nil || u == nil {
		return nil
	}
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintln(file, "# Netscape HTTP Cookie File")
	fmt.Fprintln(file, "# This file was generated by aiscan curl. Edit at your own risk.")
	fmt.Fprintln(file)
	for _, cookie := range jar.Cookies(u) {
		fmt.Fprintf(file, "%s\tFALSE\t/\tFALSE\t0\t%s\t%s\n", u.Hostname(), cookie.Name, cookie.Value)
	}
	return nil
}
