// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package aop

type ImageSource struct {
	// Base64 corresponds to the JSON schema field "base64".
	Base64 string `json:"base64,omitempty,omitzero"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type,omitempty,omitzero"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path,omitempty,omitzero"`
}

type MessageData struct {
	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id"`

	// Parts corresponds to the JSON schema field "parts".
	Parts []MessagePart `json:"parts"`

	// Role corresponds to the JSON schema field "role".
	Role string `json:"role"`
}

type MessagePart struct {
	// Image corresponds to the JSON schema field "image".
	Image *ImageSource `json:"image,omitempty,omitzero"`

	// Text corresponds to the JSON schema field "text".
	Text string `json:"text,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}
