// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package aop

type MessageDeltaData struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id"`

	// PartIndex corresponds to the JSON schema field "part_index".
	PartIndex int `json:"part_index"`

	// PartType corresponds to the JSON schema field "part_type".
	PartType string `json:"part_type"`
}
