// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package aop

type ErrorData struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code,omitempty,omitzero"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Retryable corresponds to the JSON schema field "retryable".
	Retryable bool `json:"retryable,omitempty,omitzero"`
}
