package aop

//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_message.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/message.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_message_delta.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/message.delta.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_tool_call.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/tool.call.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_tool_result.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/tool.result.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_usage_session.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/usage.schema.json ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/session.end.schema.json ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/turn.end.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_session_start.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/session.start.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_turn.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/turn.start.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_error.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/error.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o gen_status.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/events/status.schema.json
//go:generate go run github.com/atombender/go-jsonschema@v0.23.1 --only-models --tags json --struct-name-from-title --capitalization ID --capitalization LLM --capitalization AOP -p aop -o ext_types_gen.go ../../web/frontend/cyber-ui/packages/agent-protocol/schema/ext/aop.schema.json
