// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aop/chat.proto

package aopconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	aop "github.com/chainreactors/aiscan/aop"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "aop.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceOpenSessionProcedure is the fully-qualified name of the ChatService's OpenSession RPC.
	ChatServiceOpenSessionProcedure = "/aop.ChatService/OpenSession"
	// ChatServiceRunTurnProcedure is the fully-qualified name of the ChatService's RunTurn RPC.
	ChatServiceRunTurnProcedure = "/aop.ChatService/RunTurn"
	// ChatServiceCancelTurnProcedure is the fully-qualified name of the ChatService's CancelTurn RPC.
	ChatServiceCancelTurnProcedure = "/aop.ChatService/CancelTurn"
	// ChatServiceCloseSessionProcedure is the fully-qualified name of the ChatService's CloseSession
	// RPC.
	ChatServiceCloseSessionProcedure = "/aop.ChatService/CloseSession"
	// ChatServiceWatchEventsProcedure is the fully-qualified name of the ChatService's WatchEvents RPC.
	ChatServiceWatchEventsProcedure = "/aop.ChatService/WatchEvents"
	// ChatServiceListEventsProcedure is the fully-qualified name of the ChatService's ListEvents RPC.
	ChatServiceListEventsProcedure = "/aop.ChatService/ListEvents"
)

// ChatServiceClient is a client for the aop.ChatService service.
type ChatServiceClient interface {
	OpenSession(context.Context, *connect.Request[aop.OpenSessionRequest]) (*connect.Response[aop.OpenSessionResponse], error)
	RunTurn(context.Context, *connect.Request[aop.RunTurnRequest]) (*connect.Response[aop.RunTurnResponse], error)
	CancelTurn(context.Context, *connect.Request[aop.CancelTurnRequest]) (*connect.Response[aop.CancelTurnResponse], error)
	CloseSession(context.Context, *connect.Request[aop.CloseSessionRequest]) (*connect.Response[aop.CloseSessionResponse], error)
	WatchEvents(context.Context, *connect.Request[aop.WatchEventsRequest]) (*connect.ServerStreamForClient[aop.WatchEventsResponse], error)
	ListEvents(context.Context, *connect.Request[aop.ListEventsRequest]) (*connect.Response[aop.ListEventsResponse], error)
}

// NewChatServiceClient constructs a client for the aop.ChatService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := aop.File_aop_chat_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		openSession: connect.NewClient[aop.OpenSessionRequest, aop.OpenSessionResponse](
			httpClient,
			baseURL+ChatServiceOpenSessionProcedure,
			connect.WithSchema(chatServiceMethods.ByName("OpenSession")),
			connect.WithClientOptions(opts...),
		),
		runTurn: connect.NewClient[aop.RunTurnRequest, aop.RunTurnResponse](
			httpClient,
			baseURL+ChatServiceRunTurnProcedure,
			connect.WithSchema(chatServiceMethods.ByName("RunTurn")),
			connect.WithClientOptions(opts...),
		),
		cancelTurn: connect.NewClient[aop.CancelTurnRequest, aop.CancelTurnResponse](
			httpClient,
			baseURL+ChatServiceCancelTurnProcedure,
			connect.WithSchema(chatServiceMethods.ByName("CancelTurn")),
			connect.WithClientOptions(opts...),
		),
		closeSession: connect.NewClient[aop.CloseSessionRequest, aop.CloseSessionResponse](
			httpClient,
			baseURL+ChatServiceCloseSessionProcedure,
			connect.WithSchema(chatServiceMethods.ByName("CloseSession")),
			connect.WithClientOptions(opts...),
		),
		watchEvents: connect.NewClient[aop.WatchEventsRequest, aop.WatchEventsResponse](
			httpClient,
			baseURL+ChatServiceWatchEventsProcedure,
			connect.WithSchema(chatServiceMethods.ByName("WatchEvents")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[aop.ListEventsRequest, aop.ListEventsResponse](
			httpClient,
			baseURL+ChatServiceListEventsProcedure,
			connect.WithSchema(chatServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	openSession  *connect.Client[aop.OpenSessionRequest, aop.OpenSessionResponse]
	runTurn      *connect.Client[aop.RunTurnRequest, aop.RunTurnResponse]
	cancelTurn   *connect.Client[aop.CancelTurnRequest, aop.CancelTurnResponse]
	closeSession *connect.Client[aop.CloseSessionRequest, aop.CloseSessionResponse]
	watchEvents  *connect.Client[aop.WatchEventsRequest, aop.WatchEventsResponse]
	listEvents   *connect.Client[aop.ListEventsRequest, aop.ListEventsResponse]
}

// OpenSession calls aop.ChatService.OpenSession.
func (c *chatServiceClient) OpenSession(ctx context.Context, req *connect.Request[aop.OpenSessionRequest]) (*connect.Response[aop.OpenSessionResponse], error) {
	return c.openSession.CallUnary(ctx, req)
}

// RunTurn calls aop.ChatService.RunTurn.
func (c *chatServiceClient) RunTurn(ctx context.Context, req *connect.Request[aop.RunTurnRequest]) (*connect.Response[aop.RunTurnResponse], error) {
	return c.runTurn.CallUnary(ctx, req)
}

// CancelTurn calls aop.ChatService.CancelTurn.
func (c *chatServiceClient) CancelTurn(ctx context.Context, req *connect.Request[aop.CancelTurnRequest]) (*connect.Response[aop.CancelTurnResponse], error) {
	return c.cancelTurn.CallUnary(ctx, req)
}

// CloseSession calls aop.ChatService.CloseSession.
func (c *chatServiceClient) CloseSession(ctx context.Context, req *connect.Request[aop.CloseSessionRequest]) (*connect.Response[aop.CloseSessionResponse], error) {
	return c.closeSession.CallUnary(ctx, req)
}

// WatchEvents calls aop.ChatService.WatchEvents.
func (c *chatServiceClient) WatchEvents(ctx context.Context, req *connect.Request[aop.WatchEventsRequest]) (*connect.ServerStreamForClient[aop.WatchEventsResponse], error) {
	return c.watchEvents.CallServerStream(ctx, req)
}

// ListEvents calls aop.ChatService.ListEvents.
func (c *chatServiceClient) ListEvents(ctx context.Context, req *connect.Request[aop.ListEventsRequest]) (*connect.Response[aop.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ChatServiceHandler is an implementation of the aop.ChatService service.
type ChatServiceHandler interface {
	OpenSession(context.Context, *connect.Request[aop.OpenSessionRequest]) (*connect.Response[aop.OpenSessionResponse], error)
	RunTurn(context.Context, *connect.Request[aop.RunTurnRequest]) (*connect.Response[aop.RunTurnResponse], error)
	CancelTurn(context.Context, *connect.Request[aop.CancelTurnRequest]) (*connect.Response[aop.CancelTurnResponse], error)
	CloseSession(context.Context, *connect.Request[aop.CloseSessionRequest]) (*connect.Response[aop.CloseSessionResponse], error)
	WatchEvents(context.Context, *connect.Request[aop.WatchEventsRequest], *connect.ServerStream[aop.WatchEventsResponse]) error
	ListEvents(context.Context, *connect.Request[aop.ListEventsRequest]) (*connect.Response[aop.ListEventsResponse], error)
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := aop.File_aop_chat_proto.Services().ByName("ChatService").Methods()
	chatServiceOpenSessionHandler := connect.NewUnaryHandler(
		ChatServiceOpenSessionProcedure,
		svc.OpenSession,
		connect.WithSchema(chatServiceMethods.ByName("OpenSession")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceRunTurnHandler := connect.NewUnaryHandler(
		ChatServiceRunTurnProcedure,
		svc.RunTurn,
		connect.WithSchema(chatServiceMethods.ByName("RunTurn")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceCancelTurnHandler := connect.NewUnaryHandler(
		ChatServiceCancelTurnProcedure,
		svc.CancelTurn,
		connect.WithSchema(chatServiceMethods.ByName("CancelTurn")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceCloseSessionHandler := connect.NewUnaryHandler(
		ChatServiceCloseSessionProcedure,
		svc.CloseSession,
		connect.WithSchema(chatServiceMethods.ByName("CloseSession")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceWatchEventsHandler := connect.NewServerStreamHandler(
		ChatServiceWatchEventsProcedure,
		svc.WatchEvents,
		connect.WithSchema(chatServiceMethods.ByName("WatchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceListEventsHandler := connect.NewUnaryHandler(
		ChatServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(chatServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aop.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceOpenSessionProcedure:
			chatServiceOpenSessionHandler.ServeHTTP(w, r)
		case ChatServiceRunTurnProcedure:
			chatServiceRunTurnHandler.ServeHTTP(w, r)
		case ChatServiceCancelTurnProcedure:
			chatServiceCancelTurnHandler.ServeHTTP(w, r)
		case ChatServiceCloseSessionProcedure:
			chatServiceCloseSessionHandler.ServeHTTP(w, r)
		case ChatServiceWatchEventsProcedure:
			chatServiceWatchEventsHandler.ServeHTTP(w, r)
		case ChatServiceListEventsProcedure:
			chatServiceListEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) OpenSession(context.Context, *connect.Request[aop.OpenSessionRequest]) (*connect.Response[aop.OpenSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.OpenSession is not implemented"))
}

func (UnimplementedChatServiceHandler) RunTurn(context.Context, *connect.Request[aop.RunTurnRequest]) (*connect.Response[aop.RunTurnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.RunTurn is not implemented"))
}

func (UnimplementedChatServiceHandler) CancelTurn(context.Context, *connect.Request[aop.CancelTurnRequest]) (*connect.Response[aop.CancelTurnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.CancelTurn is not implemented"))
}

func (UnimplementedChatServiceHandler) CloseSession(context.Context, *connect.Request[aop.CloseSessionRequest]) (*connect.Response[aop.CloseSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.CloseSession is not implemented"))
}

func (UnimplementedChatServiceHandler) WatchEvents(context.Context, *connect.Request[aop.WatchEventsRequest], *connect.ServerStream[aop.WatchEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.WatchEvents is not implemented"))
}

func (UnimplementedChatServiceHandler) ListEvents(context.Context, *connect.Request[aop.ListEventsRequest]) (*connect.Response[aop.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aop.ChatService.ListEvents is not implemented"))
}
