// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/artifact.proto

package types

import (
	aop "github.com/chainreactors/cyber/aop"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncArtifactsRequest appends browser-originated raw artifacts and resumes
// the same archive by cursor. Browser uploads accept aop.tool.Artifact events.
type SyncArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterCursor   string                 `protobuf:"bytes,1,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	Artifacts     []*aop.Event           `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncArtifactsRequest) Reset() {
	*x = SyncArtifactsRequest{}
	mi := &file_types_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncArtifactsRequest) ProtoMessage() {}

func (x *SyncArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncArtifactsRequest.ProtoReflect.Descriptor instead.
func (*SyncArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_types_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *SyncArtifactsRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

func (x *SyncArtifactsRequest) GetArtifacts() []*aop.Event {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type SyncArtifactsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original Artifact and associated Loot events, including operation refs.
	Artifacts     []*aop.EventDelivery `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncArtifactsResponse) Reset() {
	*x = SyncArtifactsResponse{}
	mi := &file_types_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncArtifactsResponse) ProtoMessage() {}

func (x *SyncArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncArtifactsResponse.ProtoReflect.Descriptor instead.
func (*SyncArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_types_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *SyncArtifactsResponse) GetArtifacts() []*aop.EventDelivery {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

var File_types_artifact_proto protoreflect.FileDescriptor

const file_types_artifact_proto_rawDesc = "" +
	"\n" +
	"\x14types/artifact.proto\x12\x0ecyber.artifact\x1a\x0eaop/chat.proto\x1a\x0faop/event.proto\"c\n" +
	"\x14SyncArtifactsRequest\x12!\n" +
	"\fafter_cursor\x18\x01 \x01(\tR\vafterCursor\x12(\n" +
	"\tartifacts\x18\x02 \x03(\v2\n" +
	".aop.EventR\tartifacts\"I\n" +
	"\x15SyncArtifactsResponse\x120\n" +
	"\tartifacts\x18\x01 \x03(\v2\x12.aop.EventDeliveryR\tartifactsB1Z/github.com/chainreactors/cyber/core/types;typesb\x06proto3"

var (
	file_types_artifact_proto_rawDescOnce sync.Once
	file_types_artifact_proto_rawDescData []byte
)

func file_types_artifact_proto_rawDescGZIP() []byte {
	file_types_artifact_proto_rawDescOnce.Do(func() {
		file_types_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_artifact_proto_rawDesc), len(file_types_artifact_proto_rawDesc)))
	})
	return file_types_artifact_proto_rawDescData
}

var file_types_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_artifact_proto_goTypes = []any{
	(*SyncArtifactsRequest)(nil),  // 0: cyber.artifact.SyncArtifactsRequest
	(*SyncArtifactsResponse)(nil), // 1: cyber.artifact.SyncArtifactsResponse
	(*aop.Event)(nil),             // 2: aop.Event
	(*aop.EventDelivery)(nil),     // 3: aop.EventDelivery
}
var file_types_artifact_proto_depIdxs = []int32{
	2, // 0: cyber.artifact.SyncArtifactsRequest.artifacts:type_name -> aop.Event
	3, // 1: cyber.artifact.SyncArtifactsResponse.artifacts:type_name -> aop.EventDelivery
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_artifact_proto_init() }
func file_types_artifact_proto_init() {
	if File_types_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_artifact_proto_rawDesc), len(file_types_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_artifact_proto_goTypes,
		DependencyIndexes: file_types_artifact_proto_depIdxs,
		MessageInfos:      file_types_artifact_proto_msgTypes,
	}.Build()
	File_types_artifact_proto = out.File
	file_types_artifact_proto_goTypes = nil
	file_types_artifact_proto_depIdxs = nil
}
