// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/config.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributeConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Llm           *LLMConfig                  `protobuf:"bytes,1,opt,name=llm,proto3" json:"llm,omitempty"`
	Search        *SearchConfig               `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	Agent         *AgentConfig                `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	Extensions    map[string]*structpb.Struct `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Node          *NodeConfig                 `protobuf:"bytes,9,opt,name=node,proto3" json:"node,omitempty"`
	Traffic       *TrafficConfig              `protobuf:"bytes,10,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributeConfig) Reset() {
	*x = DistributeConfig{}
	mi := &file_types_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeConfig) ProtoMessage() {}

func (x *DistributeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeConfig.ProtoReflect.Descriptor instead.
func (*DistributeConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{0}
}

func (x *DistributeConfig) GetLlm() *LLMConfig {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *DistributeConfig) GetSearch() *SearchConfig {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *DistributeConfig) GetAgent() *AgentConfig {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *DistributeConfig) GetExtensions() map[string]*structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *DistributeConfig) GetNode() *NodeConfig {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *DistributeConfig) GetTraffic() *TrafficConfig {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_types_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{1}
}

func (x *NodeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LLMConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveProfile string                 `protobuf:"bytes,1,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	Providers     []*LLMProviderConfig   `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMConfig) Reset() {
	*x = LLMConfig{}
	mi := &file_types_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMConfig) ProtoMessage() {}

func (x *LLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMConfig.ProtoReflect.Descriptor instead.
func (*LLMConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{2}
}

func (x *LLMConfig) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *LLMConfig) GetProviders() []*LLMProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

type LLMProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Proxy         string                 `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow int32                  `protobuf:"varint,9,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	Timeout       int32                  `protobuf:"varint,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Images        *bool                  `protobuf:"varint,11,opt,name=images,proto3,oneof" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMProviderConfig) Reset() {
	*x = LLMProviderConfig{}
	mi := &file_types_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderConfig) ProtoMessage() {}

func (x *LLMProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderConfig.ProtoReflect.Descriptor instead.
func (*LLMProviderConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{3}
}

func (x *LLMProviderConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMProviderConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMProviderConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMProviderConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProviderConfig) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *LLMProviderConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMProviderConfig) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *LLMProviderConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *LLMProviderConfig) GetImages() bool {
	if x != nil && x.Images != nil {
		return *x.Images
	}
	return false
}

type SearchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TavilyKeys    string                 `protobuf:"bytes,1,opt,name=tavily_keys,json=tavilyKeys,proto3" json:"tavily_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConfig) Reset() {
	*x = SearchConfig{}
	mi := &file_types_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConfig) ProtoMessage() {}

func (x *SearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConfig.ProtoReflect.Descriptor instead.
func (*SearchConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{4}
}

func (x *SearchConfig) GetTavilyKeys() string {
	if x != nil {
		return x.TavilyKeys
	}
	return ""
}

type AgentConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Tools                 []string               `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	Timeout               *int32                 `protobuf:"varint,2,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	Heartbeat             int32                  `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	EvalCriteria          string                 `protobuf:"bytes,5,opt,name=eval_criteria,json=evalCriteria,proto3" json:"eval_criteria,omitempty"`
	EvalModel             string                 `protobuf:"bytes,6,opt,name=eval_model,json=evalModel,proto3" json:"eval_model,omitempty"`
	EvalRounds            string                 `protobuf:"bytes,7,opt,name=eval_rounds,json=evalRounds,proto3" json:"eval_rounds,omitempty"`
	CaptureProviderFrames bool                   `protobuf:"varint,8,opt,name=capture_provider_frames,json=captureProviderFrames,proto3" json:"capture_provider_frames,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_types_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{5}
}

func (x *AgentConfig) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentConfig) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *AgentConfig) GetHeartbeat() int32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *AgentConfig) GetEvalCriteria() string {
	if x != nil {
		return x.EvalCriteria
	}
	return ""
}

func (x *AgentConfig) GetEvalModel() string {
	if x != nil {
		return x.EvalModel
	}
	return ""
}

func (x *AgentConfig) GetEvalRounds() string {
	if x != nil {
		return x.EvalRounds
	}
	return ""
}

func (x *AgentConfig) GetCaptureProviderFrames() bool {
	if x != nil {
		return x.CaptureProviderFrames
	}
	return false
}

type TrafficConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BodyStorage        string                 `protobuf:"bytes,1,opt,name=body_storage,json=bodyStorage,proto3" json:"body_storage,omitempty"`
	BodyMaxBytes       int64                  `protobuf:"varint,2,opt,name=body_max_bytes,json=bodyMaxBytes,proto3" json:"body_max_bytes,omitempty"`
	BodyRetentionBytes int64                  `protobuf:"varint,3,opt,name=body_retention_bytes,json=bodyRetentionBytes,proto3" json:"body_retention_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TrafficConfig) Reset() {
	*x = TrafficConfig{}
	mi := &file_types_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficConfig) ProtoMessage() {}

func (x *TrafficConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficConfig.ProtoReflect.Descriptor instead.
func (*TrafficConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficConfig) GetBodyStorage() string {
	if x != nil {
		return x.BodyStorage
	}
	return ""
}

func (x *TrafficConfig) GetBodyMaxBytes() int64 {
	if x != nil {
		return x.BodyMaxBytes
	}
	return 0
}

func (x *TrafficConfig) GetBodyRetentionBytes() int64 {
	if x != nil {
		return x.BodyRetentionBytes
	}
	return 0
}

type LLMProviderView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl          string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKeyConfigured bool                   `protobuf:"varint,5,opt,name=api_key_configured,json=apiKeyConfigured,proto3" json:"api_key_configured,omitempty"`
	Model            string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Proxy            string                 `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	MaxTokens        int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow    int32                  `protobuf:"varint,9,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	Timeout          int32                  `protobuf:"varint,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Images           *bool                  `protobuf:"varint,11,opt,name=images,proto3,oneof" json:"images,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLMProviderView) Reset() {
	*x = LLMProviderView{}
	mi := &file_types_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProviderView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderView) ProtoMessage() {}

func (x *LLMProviderView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderView.ProtoReflect.Descriptor instead.
func (*LLMProviderView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{7}
}

func (x *LLMProviderView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMProviderView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMProviderView) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProviderView) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProviderView) GetApiKeyConfigured() bool {
	if x != nil {
		return x.ApiKeyConfigured
	}
	return false
}

func (x *LLMProviderView) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProviderView) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *LLMProviderView) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMProviderView) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *LLMProviderView) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *LLMProviderView) GetImages() bool {
	if x != nil && x.Images != nil {
		return *x.Images
	}
	return false
}

type LLMView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveProfile string                 `protobuf:"bytes,1,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	Active        *LLMProviderView       `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	Providers     []*LLMProviderView     `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMView) Reset() {
	*x = LLMView{}
	mi := &file_types_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMView) ProtoMessage() {}

func (x *LLMView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMView.ProtoReflect.Descriptor instead.
func (*LLMView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{8}
}

func (x *LLMView) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *LLMView) GetActive() *LLMProviderView {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *LLMView) GetProviders() []*LLMProviderView {
	if x != nil {
		return x.Providers
	}
	return nil
}

type SearchView struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TavilyKeysConfigured bool                   `protobuf:"varint,1,opt,name=tavily_keys_configured,json=tavilyKeysConfigured,proto3" json:"tavily_keys_configured,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SearchView) Reset() {
	*x = SearchView{}
	mi := &file_types_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchView) ProtoMessage() {}

func (x *SearchView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchView.ProtoReflect.Descriptor instead.
func (*SearchView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{9}
}

func (x *SearchView) GetTavilyKeysConfigured() bool {
	if x != nil {
		return x.TavilyKeysConfigured
	}
	return false
}

type ConfigView struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Path          string                    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Loaded        bool                      `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Llm           *LLMView                  `protobuf:"bytes,3,opt,name=llm,proto3" json:"llm,omitempty"`
	Search        *SearchView               `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	Agent         *AgentConfig              `protobuf:"bytes,9,opt,name=agent,proto3" json:"agent,omitempty"`
	Extensions    map[string]*ExtensionView `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Traffic       *TrafficConfig            `protobuf:"bytes,11,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigView) Reset() {
	*x = ConfigView{}
	mi := &file_types_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigView) ProtoMessage() {}

func (x *ConfigView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigView.ProtoReflect.Descriptor instead.
func (*ConfigView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigView) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigView) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ConfigView) GetLlm() *LLMView {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *ConfigView) GetSearch() *SearchView {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ConfigView) GetAgent() *AgentConfig {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ConfigView) GetExtensions() map[string]*ExtensionView {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ConfigView) GetTraffic() *TrafficConfig {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_types_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{11}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigView            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_types_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *DistributeConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_types_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigRequest) GetConfig() *DistributeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigView            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_types_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateConfigResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type ActivateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProfileRequest) Reset() {
	*x = ActivateProfileRequest{}
	mi := &file_types_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileRequest) ProtoMessage() {}

func (x *ActivateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileRequest.ProtoReflect.Descriptor instead.
func (*ActivateProfileRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ActivateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigView            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProfileResponse) Reset() {
	*x = ActivateProfileResponse{}
	mi := &file_types_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileResponse) ProtoMessage() {}

func (x *ActivateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileResponse.ProtoReflect.Descriptor instead.
func (*ActivateProfileResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{16}
}

func (x *ActivateProfileResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type LLMProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Proxy         string                 `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMProbeRequest) Reset() {
	*x = LLMProbeRequest{}
	mi := &file_types_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProbeRequest) ProtoMessage() {}

func (x *LLMProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProbeRequest.ProtoReflect.Descriptor instead.
func (*LLMProbeRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{17}
}

func (x *LLMProbeRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *LLMProbeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProbeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProbeRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMProbeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProbeRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type LLMProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Reply         string                 `protobuf:"bytes,5,opt,name=reply,proto3" json:"reply,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMProbeResult) Reset() {
	*x = LLMProbeResult{}
	mi := &file_types_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProbeResult) ProtoMessage() {}

func (x *LLMProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProbeResult.ProtoReflect.Descriptor instead.
func (*LLMProbeResult) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{18}
}

func (x *LLMProbeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LLMProbeResult) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProbeResult) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProbeResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LLMProbeResult) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *LLMProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListModelsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Supported     bool                   `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	Models        []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResult) Reset() {
	*x = ListModelsResult{}
	mi := &file_types_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResult) ProtoMessage() {}

func (x *ListModelsResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResult.ProtoReflect.Descriptor instead.
func (*ListModelsResult) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{19}
}

func (x *ListModelsResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListModelsResult) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *ListModelsResult) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Config        *DistributeConfig      `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_types_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{20}
}

func (x *TestConnectionRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *TestConnectionRequest) GetConfig() *DistributeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConnectionCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionCheck) Reset() {
	*x = ConnectionCheck{}
	mi := &file_types_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionCheck) ProtoMessage() {}

func (x *ConnectionCheck) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionCheck.ProtoReflect.Descriptor instead.
func (*ConnectionCheck) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{21}
}

func (x *ConnectionCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionCheck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectionCheck) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ConnectionCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ConnectionCheck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*ConnectionCheck     `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_types_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{22}
}

func (x *TestConnectionResponse) GetChecks() []*ConnectionCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type ExtensionView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Values            *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	ConfiguredSecrets []string               `protobuf:"bytes,2,rep,name=configured_secrets,json=configuredSecrets,proto3" json:"configured_secrets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtensionView) Reset() {
	*x = ExtensionView{}
	mi := &file_types_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionView) ProtoMessage() {}

func (x *ExtensionView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionView.ProtoReflect.Descriptor instead.
func (*ExtensionView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{23}
}

func (x *ExtensionView) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ExtensionView) GetConfiguredSecrets() []string {
	if x != nil {
		return x.ConfiguredSecrets
	}
	return nil
}

var File_types_config_proto protoreflect.FileDescriptor

const file_types_config_proto_rawDesc = "" +
	"\n" +
	"\x12types/config.proto\x12\fcyber.config\x1a\x1cgoogle/protobuf/struct.proto\"\xcc\x03\n" +
	"\x10DistributeConfig\x12)\n" +
	"\x03llm\x18\x01 \x01(\v2\x17.cyber.config.LLMConfigR\x03llm\x122\n" +
	"\x06search\x18\x05 \x01(\v2\x1a.cyber.config.SearchConfigR\x06search\x12/\n" +
	"\x05agent\x18\a \x01(\v2\x19.cyber.config.AgentConfigR\x05agent\x12N\n" +
	"\n" +
	"extensions\x18\b \x03(\v2..cyber.config.DistributeConfig.ExtensionsEntryR\n" +
	"extensions\x12,\n" +
	"\x04node\x18\t \x01(\v2\x18.cyber.config.NodeConfigR\x04node\x125\n" +
	"\atraffic\x18\n" +
	" \x01(\v2\x1b.cyber.config.TrafficConfigR\atraffic\x1aV\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x06\x10\aR\x03ioa\"0\n" +
	"\n" +
	"NodeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"q\n" +
	"\tLLMConfig\x12%\n" +
	"\x0eactive_profile\x18\x01 \x01(\tR\ractiveProfile\x12=\n" +
	"\tproviders\x18\x02 \x03(\v2\x1f.cyber.config.LLMProviderConfigR\tproviders\"\xbb\x02\n" +
	"\x11LLMProviderConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05proxy\x18\a \x01(\tR\x05proxy\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0econtext_window\x18\t \x01(\x05R\rcontextWindow\x12\x18\n" +
	"\atimeout\x18\n" +
	" \x01(\x05R\atimeout\x12\x1b\n" +
	"\x06images\x18\v \x01(\bH\x00R\x06images\x88\x01\x01B\t\n" +
	"\a_images\"/\n" +
	"\fSearchConfig\x12\x1f\n" +
	"\vtavily_keys\x18\x01 \x01(\tR\n" +
	"tavilyKeys\"\x8f\x02\n" +
	"\vAgentConfig\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools\x12\x1d\n" +
	"\atimeout\x18\x02 \x01(\x05H\x00R\atimeout\x88\x01\x01\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\x05R\theartbeat\x12#\n" +
	"\reval_criteria\x18\x05 \x01(\tR\fevalCriteria\x12\x1d\n" +
	"\n" +
	"eval_model\x18\x06 \x01(\tR\tevalModel\x12\x1f\n" +
	"\veval_rounds\x18\a \x01(\tR\n" +
	"evalRounds\x126\n" +
	"\x17capture_provider_frames\x18\b \x01(\bR\x15captureProviderFramesB\n" +
	"\n" +
	"\b_timeoutJ\x04\b\x03\x10\x04\"\x8a\x01\n" +
	"\rTrafficConfig\x12!\n" +
	"\fbody_storage\x18\x01 \x01(\tR\vbodyStorage\x12$\n" +
	"\x0ebody_max_bytes\x18\x02 \x01(\x03R\fbodyMaxBytes\x120\n" +
	"\x14body_retention_bytes\x18\x03 \x01(\x03R\x12bodyRetentionBytes\"\xce\x02\n" +
	"\x0fLLMProviderView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12,\n" +
	"\x12api_key_configured\x18\x05 \x01(\bR\x10apiKeyConfigured\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05proxy\x18\a \x01(\tR\x05proxy\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0econtext_window\x18\t \x01(\x05R\rcontextWindow\x12\x18\n" +
	"\atimeout\x18\n" +
	" \x01(\x05R\atimeout\x12\x1b\n" +
	"\x06images\x18\v \x01(\bH\x00R\x06images\x88\x01\x01B\t\n" +
	"\a_images\"\xa4\x01\n" +
	"\aLLMView\x12%\n" +
	"\x0eactive_profile\x18\x01 \x01(\tR\ractiveProfile\x125\n" +
	"\x06active\x18\x02 \x01(\v2\x1d.cyber.config.LLMProviderViewR\x06active\x12;\n" +
	"\tproviders\x18\x03 \x03(\v2\x1d.cyber.config.LLMProviderViewR\tproviders\"B\n" +
	"\n" +
	"SearchView\x124\n" +
	"\x16tavily_keys_configured\x18\x01 \x01(\bR\x14tavilyKeysConfigured\"\xbe\x03\n" +
	"\n" +
	"ConfigView\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06loaded\x18\x02 \x01(\bR\x06loaded\x12'\n" +
	"\x03llm\x18\x03 \x01(\v2\x15.cyber.config.LLMViewR\x03llm\x120\n" +
	"\x06search\x18\a \x01(\v2\x18.cyber.config.SearchViewR\x06search\x12/\n" +
	"\x05agent\x18\t \x01(\v2\x19.cyber.config.AgentConfigR\x05agent\x12H\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2(.cyber.config.ConfigView.ExtensionsEntryR\n" +
	"extensions\x125\n" +
	"\atraffic\x18\v \x01(\v2\x1b.cyber.config.TrafficConfigR\atraffic\x1aZ\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.cyber.config.ExtensionViewR\x05value:\x028\x01J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\b\x10\tR\x03ioa\"\x12\n" +
	"\x10GetConfigRequest\"E\n" +
	"\x11GetConfigResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.cyber.config.ConfigViewR\x06config\"M\n" +
	"\x13UpdateConfigRequest\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1e.cyber.config.DistributeConfigR\x06config\"H\n" +
	"\x14UpdateConfigResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.cyber.config.ConfigViewR\x06config\"7\n" +
	"\x16ActivateProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"K\n" +
	"\x17ActivateProfileResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.cyber.config.ConfigViewR\x06config\"\xac\x01\n" +
	"\x0fLLMProbeRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05proxy\x18\x06 \x01(\tR\x05proxy\"\x9d\x01\n" +
	"\x0eLLMProbeResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05reply\x18\x05 \x01(\tR\x05reply\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"n\n" +
	"\x10ListModelsResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tsupported\x18\x02 \x01(\bR\tsupported\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"i\n" +
	"\x15TestConnectionRequest\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.cyber.config.DistributeConfigR\x06config\"\x82\x01\n" +
	"\x0fConnectionCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"O\n" +
	"\x16TestConnectionResponse\x125\n" +
	"\x06checks\x18\x01 \x03(\v2\x1d.cyber.config.ConnectionCheckR\x06checks\"o\n" +
	"\rExtensionView\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\x12-\n" +
	"\x12configured_secrets\x18\x02 \x03(\tR\x11configuredSecretsB1Z/github.com/chainreactors/cyber/core/types;typesb\x06proto3"

var (
	file_types_config_proto_rawDescOnce sync.Once
	file_types_config_proto_rawDescData []byte
)

func file_types_config_proto_rawDescGZIP() []byte {
	file_types_config_proto_rawDescOnce.Do(func() {
		file_types_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_config_proto_rawDesc), len(file_types_config_proto_rawDesc)))
	})
	return file_types_config_proto_rawDescData
}

var file_types_config_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_types_config_proto_goTypes = []any{
	(*DistributeConfig)(nil),        // 0: cyber.config.DistributeConfig
	(*NodeConfig)(nil),              // 1: cyber.config.NodeConfig
	(*LLMConfig)(nil),               // 2: cyber.config.LLMConfig
	(*LLMProviderConfig)(nil),       // 3: cyber.config.LLMProviderConfig
	(*SearchConfig)(nil),            // 4: cyber.config.SearchConfig
	(*AgentConfig)(nil),             // 5: cyber.config.AgentConfig
	(*TrafficConfig)(nil),           // 6: cyber.config.TrafficConfig
	(*LLMProviderView)(nil),         // 7: cyber.config.LLMProviderView
	(*LLMView)(nil),                 // 8: cyber.config.LLMView
	(*SearchView)(nil),              // 9: cyber.config.SearchView
	(*ConfigView)(nil),              // 10: cyber.config.ConfigView
	(*GetConfigRequest)(nil),        // 11: cyber.config.GetConfigRequest
	(*GetConfigResponse)(nil),       // 12: cyber.config.GetConfigResponse
	(*UpdateConfigRequest)(nil),     // 13: cyber.config.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),    // 14: cyber.config.UpdateConfigResponse
	(*ActivateProfileRequest)(nil),  // 15: cyber.config.ActivateProfileRequest
	(*ActivateProfileResponse)(nil), // 16: cyber.config.ActivateProfileResponse
	(*LLMProbeRequest)(nil),         // 17: cyber.config.LLMProbeRequest
	(*LLMProbeResult)(nil),          // 18: cyber.config.LLMProbeResult
	(*ListModelsResult)(nil),        // 19: cyber.config.ListModelsResult
	(*TestConnectionRequest)(nil),   // 20: cyber.config.TestConnectionRequest
	(*ConnectionCheck)(nil),         // 21: cyber.config.ConnectionCheck
	(*TestConnectionResponse)(nil),  // 22: cyber.config.TestConnectionResponse
	(*ExtensionView)(nil),           // 23: cyber.config.ExtensionView
	nil,                             // 24: cyber.config.DistributeConfig.ExtensionsEntry
	nil,                             // 25: cyber.config.ConfigView.ExtensionsEntry
	(*structpb.Struct)(nil),         // 26: google.protobuf.Struct
}
var file_types_config_proto_depIdxs = []int32{
	2,  // 0: cyber.config.DistributeConfig.llm:type_name -> cyber.config.LLMConfig
	4,  // 1: cyber.config.DistributeConfig.search:type_name -> cyber.config.SearchConfig
	5,  // 2: cyber.config.DistributeConfig.agent:type_name -> cyber.config.AgentConfig
	24, // 3: cyber.config.DistributeConfig.extensions:type_name -> cyber.config.DistributeConfig.ExtensionsEntry
	1,  // 4: cyber.config.DistributeConfig.node:type_name -> cyber.config.NodeConfig
	6,  // 5: cyber.config.DistributeConfig.traffic:type_name -> cyber.config.TrafficConfig
	3,  // 6: cyber.config.LLMConfig.providers:type_name -> cyber.config.LLMProviderConfig
	7,  // 7: cyber.config.LLMView.active:type_name -> cyber.config.LLMProviderView
	7,  // 8: cyber.config.LLMView.providers:type_name -> cyber.config.LLMProviderView
	8,  // 9: cyber.config.ConfigView.llm:type_name -> cyber.config.LLMView
	9,  // 10: cyber.config.ConfigView.search:type_name -> cyber.config.SearchView
	5,  // 11: cyber.config.ConfigView.agent:type_name -> cyber.config.AgentConfig
	25, // 12: cyber.config.ConfigView.extensions:type_name -> cyber.config.ConfigView.ExtensionsEntry
	6,  // 13: cyber.config.ConfigView.traffic:type_name -> cyber.config.TrafficConfig
	10, // 14: cyber.config.GetConfigResponse.config:type_name -> cyber.config.ConfigView
	0,  // 15: cyber.config.UpdateConfigRequest.config:type_name -> cyber.config.DistributeConfig
	10, // 16: cyber.config.UpdateConfigResponse.config:type_name -> cyber.config.ConfigView
	10, // 17: cyber.config.ActivateProfileResponse.config:type_name -> cyber.config.ConfigView
	0,  // 18: cyber.config.TestConnectionRequest.config:type_name -> cyber.config.DistributeConfig
	21, // 19: cyber.config.TestConnectionResponse.checks:type_name -> cyber.config.ConnectionCheck
	26, // 20: cyber.config.ExtensionView.values:type_name -> google.protobuf.Struct
	26, // 21: cyber.config.DistributeConfig.ExtensionsEntry.value:type_name -> google.protobuf.Struct
	23, // 22: cyber.config.ConfigView.ExtensionsEntry.value:type_name -> cyber.config.ExtensionView
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_types_config_proto_init() }
func file_types_config_proto_init() {
	if File_types_config_proto != nil {
		return
	}
	file_types_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_config_proto_msgTypes[5].OneofWrappers = []any{}
	file_types_config_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_config_proto_rawDesc), len(file_types_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_config_proto_goTypes,
		DependencyIndexes: file_types_config_proto_depIdxs,
		MessageInfos:      file_types_config_proto_msgTypes,
	}.Build()
	File_types_config_proto = out.File
	file_types_config_proto_goTypes = nil
	file_types_config_proto_depIdxs = nil
}
