syntax = "proto3";

package aiscan.rpc.agent;

import "aiscan/types/agent.proto";

option go_package = "github.com/chainreactors/aiscan/pkg/rpc/agent;agent";

service AgentService {
  rpc ListAgents(aiscan.agent.ListAgentsRequest) returns (aiscan.agent.ListAgentsResponse);
  rpc ListLocalAgents(aiscan.agent.ListLocalAgentsRequest) returns (aiscan.agent.ListLocalAgentsResponse);
  rpc LaunchLocalAgent(aiscan.agent.LaunchLocalAgentRequest) returns (aiscan.agent.LaunchLocalAgentResponse);
  rpc StopLocalAgent(aiscan.agent.StopLocalAgentRequest) returns (aiscan.agent.StopLocalAgentResponse);
}
