// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: aop/tool/protocol.proto

package tool

import (
	aop "github.com/chainreactors/aiscan/aop"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TurnId        string                 `protobuf:"bytes,2,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Call          *aop.ToolCall          `protobuf:"bytes,3,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_aop_tool_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_aop_tool_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_aop_tool_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Call) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Call) GetCall() *aop.ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_aop_tool_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_aop_tool_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_aop_tool_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Progress) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Progress) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Progress) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Progress) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ProtocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ProtocolMessage_Progress
	//	*ProtocolMessage_Call
	Message       isProtocolMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_aop_tool_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aop_tool_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_aop_tool_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ProtocolMessage) GetMessage() isProtocolMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProtocolMessage) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ProtocolMessage) GetCall() *Call {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Call); ok {
			return x.Call
		}
	}
	return nil
}

type isProtocolMessage_Message interface {
	isProtocolMessage_Message()
}

type ProtocolMessage_Progress struct {
	Progress *Progress `protobuf:"bytes,10,opt,name=progress,proto3,oneof"`
}

type ProtocolMessage_Call struct {
	Call *Call `protobuf:"bytes,11,opt,name=call,proto3,oneof"`
}

func (*ProtocolMessage_Progress) isProtocolMessage_Message() {}

func (*ProtocolMessage_Call) isProtocolMessage_Message() {}

var File_aop_tool_protocol_proto protoreflect.FileDescriptor

const file_aop_tool_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17aop/tool/protocol.proto\x12\baop.tool\x1a\x11aop/content.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\x04Call\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aturn_id\x18\x02 \x01(\tR\x06turnId\x12!\n" +
	"\x04call\x18\x03 \x01(\v2\r.aop.ToolCallR\x04call\"\x90\x01\n" +
	"\bProgress\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04textJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05\"t\n" +
	"\x0fProtocolMessage\x120\n" +
	"\bprogress\x18\n" +
	" \x01(\v2\x12.aop.tool.ProgressH\x00R\bprogress\x12$\n" +
	"\x04call\x18\v \x01(\v2\x0e.aop.tool.CallH\x00R\x04callB\t\n" +
	"\amessageB/Z-github.com/chainreactors/aiscan/aop/tool;toolb\x06proto3"

var (
	file_aop_tool_protocol_proto_rawDescOnce sync.Once
	file_aop_tool_protocol_proto_rawDescData []byte
)

func file_aop_tool_protocol_proto_rawDescGZIP() []byte {
	file_aop_tool_protocol_proto_rawDescOnce.Do(func() {
		file_aop_tool_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aop_tool_protocol_proto_rawDesc), len(file_aop_tool_protocol_proto_rawDesc)))
	})
	return file_aop_tool_protocol_proto_rawDescData
}

var file_aop_tool_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aop_tool_protocol_proto_goTypes = []any{
	(*Call)(nil),                  // 0: aop.tool.Call
	(*Progress)(nil),              // 1: aop.tool.Progress
	(*ProtocolMessage)(nil),       // 2: aop.tool.ProtocolMessage
	(*aop.ToolCall)(nil),          // 3: aop.ToolCall
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_aop_tool_protocol_proto_depIdxs = []int32{
	3, // 0: aop.tool.Call.call:type_name -> aop.ToolCall
	4, // 1: aop.tool.Progress.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: aop.tool.ProtocolMessage.progress:type_name -> aop.tool.Progress
	0, // 3: aop.tool.ProtocolMessage.call:type_name -> aop.tool.Call
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aop_tool_protocol_proto_init() }
func file_aop_tool_protocol_proto_init() {
	if File_aop_tool_protocol_proto != nil {
		return
	}
	file_aop_tool_protocol_proto_msgTypes[2].OneofWrappers = []any{
		(*ProtocolMessage_Progress)(nil),
		(*ProtocolMessage_Call)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aop_tool_protocol_proto_rawDesc), len(file_aop_tool_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aop_tool_protocol_proto_goTypes,
		DependencyIndexes: file_aop_tool_protocol_proto_depIdxs,
		MessageInfos:      file_aop_tool_protocol_proto_msgTypes,
	}.Build()
	File_aop_tool_protocol_proto = out.File
	file_aop_tool_protocol_proto_goTypes = nil
	file_aop_tool_protocol_proto_depIdxs = nil
}
