// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc/aop.proto

package rpc

import (
	aop "github.com/chainreactors/aiscan/aop"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_aop_proto protoreflect.FileDescriptor

const file_rpc_aop_proto_rawDesc = "" +
	"\n" +
	"\rrpc/aop.proto\x12\x0eaiscan.rpc.aop\x1a\x12aop/envelope.proto29\n" +
	"\n" +
	"AOPService\x12+\n" +
	"\aConnect\x12\r.aop.Envelope\x1a\r.aop.Envelope(\x010\x01B-Z+github.com/chainreactors/aiscan/pkg/rpc;rpcb\x06proto3"

var file_rpc_aop_proto_goTypes = []any{
	(*aop.Envelope)(nil), // 0: aop.Envelope
}
var file_rpc_aop_proto_depIdxs = []int32{
	0, // 0: aiscan.rpc.aop.AOPService.Connect:input_type -> aop.Envelope
	0, // 1: aiscan.rpc.aop.AOPService.Connect:output_type -> aop.Envelope
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_aop_proto_init() }
func file_rpc_aop_proto_init() {
	if File_rpc_aop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_aop_proto_rawDesc), len(file_rpc_aop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_aop_proto_goTypes,
		DependencyIndexes: file_rpc_aop_proto_depIdxs,
	}.Build()
	File_rpc_aop_proto = out.File
	file_rpc_aop_proto_goTypes = nil
	file_rpc_aop_proto_depIdxs = nil
}
