// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/aop.proto

package rpc

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	aop "github.com/chainreactors/aiscan/aop"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AOPServiceName is the fully-qualified name of the AOPService service.
	AOPServiceName = "aiscan.rpc.aop.AOPService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AOPServiceConnectProcedure is the fully-qualified name of the AOPService's Connect RPC.
	AOPServiceConnectProcedure = "/aiscan.rpc.aop.AOPService/Connect"
)

// AOPServiceClient is a client for the aiscan.rpc.aop.AOPService service.
type AOPServiceClient interface {
	Connect(context.Context) *connect.BidiStreamForClient[aop.Envelope, aop.Envelope]
}

// NewAOPServiceClient constructs a client for the aiscan.rpc.aop.AOPService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAOPServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AOPServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	aOPServiceMethods := File_rpc_aop_proto.Services().ByName("AOPService").Methods()
	return &aOPServiceClient{
		connect: connect.NewClient[aop.Envelope, aop.Envelope](
			httpClient,
			baseURL+AOPServiceConnectProcedure,
			connect.WithSchema(aOPServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// aOPServiceClient implements AOPServiceClient.
type aOPServiceClient struct {
	connect *connect.Client[aop.Envelope, aop.Envelope]
}

// Connect calls aiscan.rpc.aop.AOPService.Connect.
func (c *aOPServiceClient) Connect(ctx context.Context) *connect.BidiStreamForClient[aop.Envelope, aop.Envelope] {
	return c.connect.CallBidiStream(ctx)
}

// AOPServiceHandler is an implementation of the aiscan.rpc.aop.AOPService service.
type AOPServiceHandler interface {
	Connect(context.Context, *connect.BidiStream[aop.Envelope, aop.Envelope]) error
}

// NewAOPServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAOPServiceHandler(svc AOPServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aOPServiceMethods := File_rpc_aop_proto.Services().ByName("AOPService").Methods()
	aOPServiceConnectHandler := connect.NewBidiStreamHandler(
		AOPServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(aOPServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aiscan.rpc.aop.AOPService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AOPServiceConnectProcedure:
			aOPServiceConnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAOPServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAOPServiceHandler struct{}

func (UnimplementedAOPServiceHandler) Connect(context.Context, *connect.BidiStream[aop.Envelope, aop.Envelope]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("aiscan.rpc.aop.AOPService.Connect is not implemented"))
}
