// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc/config.proto

package rpc

import (
	types "github.com/chainreactors/cyber/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_config_proto protoreflect.FileDescriptor

const file_rpc_config_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/config.proto\x12\x10cyber.rpc.config\x1a\x12types/config.proto2\x86\x04\n" +
	"\rConfigService\x12L\n" +
	"\tGetConfig\x12\x1e.cyber.config.GetConfigRequest\x1a\x1f.cyber.config.GetConfigResponse\x12U\n" +
	"\fUpdateConfig\x12!.cyber.config.UpdateConfigRequest\x1a\".cyber.config.UpdateConfigResponse\x12^\n" +
	"\x0fActivateProfile\x12$.cyber.config.ActivateProfileRequest\x1a%.cyber.config.ActivateProfileResponse\x12F\n" +
	"\aTestLLM\x12\x1d.cyber.config.LLMProbeRequest\x1a\x1c.cyber.config.LLMProbeResult\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.cyber.config.LLMProbeRequest\x1a\x1e.cyber.config.ListModelsResult\x12[\n" +
	"\x0eTestConnection\x12#.cyber.config.TestConnectionRequest\x1a$.cyber.config.TestConnectionResponseB,Z*github.com/chainreactors/cyber/pkg/rpc;rpcb\x06proto3"

var file_rpc_config_proto_goTypes = []any{
	(*types.GetConfigRequest)(nil),        // 0: cyber.config.GetConfigRequest
	(*types.UpdateConfigRequest)(nil),     // 1: cyber.config.UpdateConfigRequest
	(*types.ActivateProfileRequest)(nil),  // 2: cyber.config.ActivateProfileRequest
	(*types.LLMProbeRequest)(nil),         // 3: cyber.config.LLMProbeRequest
	(*types.TestConnectionRequest)(nil),   // 4: cyber.config.TestConnectionRequest
	(*types.GetConfigResponse)(nil),       // 5: cyber.config.GetConfigResponse
	(*types.UpdateConfigResponse)(nil),    // 6: cyber.config.UpdateConfigResponse
	(*types.ActivateProfileResponse)(nil), // 7: cyber.config.ActivateProfileResponse
	(*types.LLMProbeResult)(nil),          // 8: cyber.config.LLMProbeResult
	(*types.ListModelsResult)(nil),        // 9: cyber.config.ListModelsResult
	(*types.TestConnectionResponse)(nil),  // 10: cyber.config.TestConnectionResponse
}
var file_rpc_config_proto_depIdxs = []int32{
	0,  // 0: cyber.rpc.config.ConfigService.GetConfig:input_type -> cyber.config.GetConfigRequest
	1,  // 1: cyber.rpc.config.ConfigService.UpdateConfig:input_type -> cyber.config.UpdateConfigRequest
	2,  // 2: cyber.rpc.config.ConfigService.ActivateProfile:input_type -> cyber.config.ActivateProfileRequest
	3,  // 3: cyber.rpc.config.ConfigService.TestLLM:input_type -> cyber.config.LLMProbeRequest
	3,  // 4: cyber.rpc.config.ConfigService.ListModels:input_type -> cyber.config.LLMProbeRequest
	4,  // 5: cyber.rpc.config.ConfigService.TestConnection:input_type -> cyber.config.TestConnectionRequest
	5,  // 6: cyber.rpc.config.ConfigService.GetConfig:output_type -> cyber.config.GetConfigResponse
	6,  // 7: cyber.rpc.config.ConfigService.UpdateConfig:output_type -> cyber.config.UpdateConfigResponse
	7,  // 8: cyber.rpc.config.ConfigService.ActivateProfile:output_type -> cyber.config.ActivateProfileResponse
	8,  // 9: cyber.rpc.config.ConfigService.TestLLM:output_type -> cyber.config.LLMProbeResult
	9,  // 10: cyber.rpc.config.ConfigService.ListModels:output_type -> cyber.config.ListModelsResult
	10, // 11: cyber.rpc.config.ConfigService.TestConnection:output_type -> cyber.config.TestConnectionResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_config_proto_init() }
func file_rpc_config_proto_init() {
	if File_rpc_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_config_proto_rawDesc), len(file_rpc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_config_proto_goTypes,
		DependencyIndexes: file_rpc_config_proto_depIdxs,
	}.Build()
	File_rpc_config_proto = out.File
	file_rpc_config_proto_goTypes = nil
	file_rpc_config_proto_depIdxs = nil
}
