// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/agent.proto

package types

import (
	aop "github.com/chainreactors/aiscan/aop"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hello         *aop.AgentHello        `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	Status        *aop.AgentStatus       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Stats         *aop.AgentStats        `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	Commands      []*CommandSpec         `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	Busy          bool                   `protobuf:"varint,7,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentView) Reset() {
	*x = AgentView{}
	mi := &file_types_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentView) ProtoMessage() {}

func (x *AgentView) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentView.ProtoReflect.Descriptor instead.
func (*AgentView) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentView) GetHello() *aop.AgentHello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *AgentView) GetStatus() *aop.AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AgentView) GetStats() *aop.AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *AgentView) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *AgentView) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *AgentView) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_types_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{1}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentView           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_types_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsResponse) GetAgents() []*AgentView {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentRunOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvalCriteria  string                 `protobuf:"bytes,1,opt,name=eval_criteria,json=evalCriteria,proto3" json:"eval_criteria,omitempty"`
	EvalMaxRounds uint32                 `protobuf:"varint,2,opt,name=eval_max_rounds,json=evalMaxRounds,proto3" json:"eval_max_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunOptions) Reset() {
	*x = AgentRunOptions{}
	mi := &file_types_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunOptions) ProtoMessage() {}

func (x *AgentRunOptions) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunOptions.ProtoReflect.Descriptor instead.
func (*AgentRunOptions) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRunOptions) GetEvalCriteria() string {
	if x != nil {
		return x.EvalCriteria
	}
	return ""
}

func (x *AgentRunOptions) GetEvalMaxRounds() uint32 {
	if x != nil {
		return x.EvalMaxRounds
	}
	return 0
}

type CommandDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Presentation  string                 `protobuf:"bytes,2,opt,name=presentation,proto3" json:"presentation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDetail) Reset() {
	*x = CommandDetail{}
	mi := &file_types_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDetail) ProtoMessage() {}

func (x *CommandDetail) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDetail.ProtoReflect.Descriptor instead.
func (*CommandDetail) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CommandDetail) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *CommandDetail) GetPresentation() string {
	if x != nil {
		return x.Presentation
	}
	return ""
}

type CompactDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	KeptMessages  uint64                 `protobuf:"varint,2,opt,name=kept_messages,json=keptMessages,proto3" json:"kept_messages,omitempty"`
	TokensAfter   uint64                 `protobuf:"varint,3,opt,name=tokens_after,json=tokensAfter,proto3" json:"tokens_after,omitempty"`
	TokensBefore  uint64                 `protobuf:"varint,4,opt,name=tokens_before,json=tokensBefore,proto3" json:"tokens_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactDetail) Reset() {
	*x = CompactDetail{}
	mi := &file_types_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactDetail) ProtoMessage() {}

func (x *CompactDetail) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactDetail.ProtoReflect.Descriptor instead.
func (*CompactDetail) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CompactDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompactDetail) GetKeptMessages() uint64 {
	if x != nil {
		return x.KeptMessages
	}
	return 0
}

func (x *CompactDetail) GetTokensAfter() uint64 {
	if x != nil {
		return x.TokensAfter
	}
	return 0
}

func (x *CompactDetail) GetTokensBefore() uint64 {
	if x != nil {
		return x.TokensBefore
	}
	return 0
}

type DelegationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	ContextMode   string                 `protobuf:"bytes,4,opt,name=context_mode,json=contextMode,proto3" json:"context_mode,omitempty"`
	RunMode       string                 `protobuf:"bytes,5,opt,name=run_mode,json=runMode,proto3" json:"run_mode,omitempty"`
	Task          string                 `protobuf:"bytes,6,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationDetail) Reset() {
	*x = DelegationDetail{}
	mi := &file_types_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationDetail) ProtoMessage() {}

func (x *DelegationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationDetail.ProtoReflect.Descriptor instead.
func (*DelegationDetail) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DelegationDetail) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DelegationDetail) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *DelegationDetail) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *DelegationDetail) GetContextMode() string {
	if x != nil {
		return x.ContextMode
	}
	return ""
}

func (x *DelegationDetail) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *DelegationDetail) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type EvalControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      string                 `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	MaxRounds     uint32                 `protobuf:"varint,2,opt,name=max_rounds,json=maxRounds,proto3" json:"max_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalControl) Reset() {
	*x = EvalControl{}
	mi := &file_types_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalControl) ProtoMessage() {}

func (x *EvalControl) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalControl.ProtoReflect.Descriptor instead.
func (*EvalControl) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{7}
}

func (x *EvalControl) GetCriteria() string {
	if x != nil {
		return x.Criteria
	}
	return ""
}

func (x *EvalControl) GetMaxRounds() uint32 {
	if x != nil {
		return x.MaxRounds
	}
	return 0
}

type EvalDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	MaxRounds     uint32                 `protobuf:"varint,2,opt,name=max_rounds,json=maxRounds,proto3" json:"max_rounds,omitempty"`
	Pass          bool                   `protobuf:"varint,3,opt,name=pass,proto3" json:"pass,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Round         uint32                 `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalDetail) Reset() {
	*x = EvalDetail{}
	mi := &file_types_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalDetail) ProtoMessage() {}

func (x *EvalDetail) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalDetail.ProtoReflect.Descriptor instead.
func (*EvalDetail) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EvalDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EvalDetail) GetMaxRounds() uint32 {
	if x != nil {
		return x.MaxRounds
	}
	return 0
}

func (x *EvalDetail) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *EvalDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvalDetail) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type BudgetWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextTokens uint64                 `protobuf:"varint,1,opt,name=context_tokens,json=contextTokens,proto3" json:"context_tokens,omitempty"`
	TokenBudget   uint64                 `protobuf:"varint,2,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetWarning) Reset() {
	*x = BudgetWarning{}
	mi := &file_types_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetWarning) ProtoMessage() {}

func (x *BudgetWarning) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetWarning.ProtoReflect.Descriptor instead.
func (*BudgetWarning) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{9}
}

func (x *BudgetWarning) GetContextTokens() uint64 {
	if x != nil {
		return x.ContextTokens
	}
	return 0
}

func (x *BudgetWarning) GetTokenBudget() uint64 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

type LLMRequestDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      uint32                 `protobuf:"varint,2,opt,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRequestDetail) Reset() {
	*x = LLMRequestDetail{}
	mi := &file_types_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRequestDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequestDetail) ProtoMessage() {}

func (x *LLMRequestDetail) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequestDetail.ProtoReflect.Descriptor instead.
func (*LLMRequestDetail) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LLMRequestDetail) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMRequestDetail) GetMessages() uint32 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *LLMRequestDetail) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMRequestDetail) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type WebMessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebMessageMetadata) Reset() {
	*x = WebMessageMetadata{}
	mi := &file_types_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMessageMetadata) ProtoMessage() {}

func (x *WebMessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_types_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMessageMetadata.ProtoReflect.Descriptor instead.
func (*WebMessageMetadata) Descriptor() ([]byte, []int) {
	return file_types_agent_proto_rawDescGZIP(), []int{11}
}

func (x *WebMessageMetadata) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WebMessageMetadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WebMessageMetadata) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_types_agent_proto protoreflect.FileDescriptor

const file_types_agent_proto_rawDesc = "" +
	"\n" +
	"\x11types/agent.proto\x12\faiscan.agent\x1a\x12aop/protocol.proto\x1a\x13types/command.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\tAgentView\x12%\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.aop.AgentHelloR\x05hello\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.aop.AgentStatusR\x06status\x12%\n" +
	"\x05stats\x18\x03 \x01(\v2\x0f.aop.AgentStatsR\x05stats\x12=\n" +
	"\fconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x127\n" +
	"\bcommands\x18\x06 \x03(\v2\x1b.aiscan.command.CommandSpecR\bcommands\x12\x12\n" +
	"\x04busy\x18\a \x01(\bR\x04busyJ\x04\b\x04\x10\x05\"\x13\n" +
	"\x11ListAgentsRequest\"E\n" +
	"\x12ListAgentsResponse\x12/\n" +
	"\x06agents\x18\x01 \x03(\v2\x17.aiscan.agent.AgentViewR\x06agents\"^\n" +
	"\x0fAgentRunOptions\x12#\n" +
	"\reval_criteria\x18\x01 \x01(\tR\fevalCriteria\x12&\n" +
	"\x0feval_max_rounds\x18\x02 \x01(\rR\revalMaxRounds\"G\n" +
	"\rCommandDetail\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\"\n" +
	"\fpresentation\x18\x02 \x01(\tR\fpresentation\"\x92\x01\n" +
	"\rCompactDetail\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12#\n" +
	"\rkept_messages\x18\x02 \x01(\x04R\fkeptMessages\x12!\n" +
	"\ftokens_after\x18\x03 \x01(\x04R\vtokensAfter\x12#\n" +
	"\rtokens_before\x18\x04 \x01(\x04R\ftokensBefore\"\xbd\x01\n" +
	"\x10DelegationDetail\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12!\n" +
	"\fcontext_mode\x18\x04 \x01(\tR\vcontextMode\x12\x19\n" +
	"\brun_mode\x18\x05 \x01(\tR\arunMode\x12\x12\n" +
	"\x04task\x18\x06 \x01(\tR\x04task\"H\n" +
	"\vEvalControl\x12\x1a\n" +
	"\bcriteria\x18\x01 \x01(\tR\bcriteria\x12\x1d\n" +
	"\n" +
	"max_rounds\x18\x02 \x01(\rR\tmaxRounds\"\x83\x01\n" +
	"\n" +
	"EvalDetail\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"max_rounds\x18\x02 \x01(\rR\tmaxRounds\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\bR\x04pass\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05round\x18\x05 \x01(\rR\x05round\"Y\n" +
	"\rBudgetWarning\x12%\n" +
	"\x0econtext_tokens\x18\x01 \x01(\x04R\rcontextTokens\x12!\n" +
	"\ftoken_budget\x18\x02 \x01(\x04R\vtokenBudget\"{\n" +
	"\x10LLMRequestDetail\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bmessages\x18\x02 \x01(\rR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\rR\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\"r\n" +
	"\x12WebMessageMetadata\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06paramsB1Z/github.com/chainreactors/aiscan/pkg/types;typesb\x06proto3"

var (
	file_types_agent_proto_rawDescOnce sync.Once
	file_types_agent_proto_rawDescData []byte
)

func file_types_agent_proto_rawDescGZIP() []byte {
	file_types_agent_proto_rawDescOnce.Do(func() {
		file_types_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_agent_proto_rawDesc), len(file_types_agent_proto_rawDesc)))
	})
	return file_types_agent_proto_rawDescData
}

var file_types_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_types_agent_proto_goTypes = []any{
	(*AgentView)(nil),             // 0: aiscan.agent.AgentView
	(*ListAgentsRequest)(nil),     // 1: aiscan.agent.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 2: aiscan.agent.ListAgentsResponse
	(*AgentRunOptions)(nil),       // 3: aiscan.agent.AgentRunOptions
	(*CommandDetail)(nil),         // 4: aiscan.agent.CommandDetail
	(*CompactDetail)(nil),         // 5: aiscan.agent.CompactDetail
	(*DelegationDetail)(nil),      // 6: aiscan.agent.DelegationDetail
	(*EvalControl)(nil),           // 7: aiscan.agent.EvalControl
	(*EvalDetail)(nil),            // 8: aiscan.agent.EvalDetail
	(*BudgetWarning)(nil),         // 9: aiscan.agent.BudgetWarning
	(*LLMRequestDetail)(nil),      // 10: aiscan.agent.LLMRequestDetail
	(*WebMessageMetadata)(nil),    // 11: aiscan.agent.WebMessageMetadata
	(*aop.AgentHello)(nil),        // 12: aop.AgentHello
	(*aop.AgentStatus)(nil),       // 13: aop.AgentStatus
	(*aop.AgentStats)(nil),        // 14: aop.AgentStats
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*CommandSpec)(nil),           // 16: aiscan.command.CommandSpec
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
}
var file_types_agent_proto_depIdxs = []int32{
	12, // 0: aiscan.agent.AgentView.hello:type_name -> aop.AgentHello
	13, // 1: aiscan.agent.AgentView.status:type_name -> aop.AgentStatus
	14, // 2: aiscan.agent.AgentView.stats:type_name -> aop.AgentStats
	15, // 3: aiscan.agent.AgentView.connected_at:type_name -> google.protobuf.Timestamp
	16, // 4: aiscan.agent.AgentView.commands:type_name -> aiscan.command.CommandSpec
	0,  // 5: aiscan.agent.ListAgentsResponse.agents:type_name -> aiscan.agent.AgentView
	17, // 6: aiscan.agent.WebMessageMetadata.params:type_name -> google.protobuf.Struct
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_types_agent_proto_init() }
func file_types_agent_proto_init() {
	if File_types_agent_proto != nil {
		return
	}
	file_types_command_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_agent_proto_rawDesc), len(file_types_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_agent_proto_goTypes,
		DependencyIndexes: file_types_agent_proto_depIdxs,
		MessageInfos:      file_types_agent_proto_msgTypes,
	}.Build()
	File_types_agent_proto = out.File
	file_types_agent_proto_goTypes = nil
	file_types_agent_proto_depIdxs = nil
}
