// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/command.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aliases       []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_types_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{0}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CommandSpec) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CommandSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CommandCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandSpec         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandCatalog) Reset() {
	*x = CommandCatalog{}
	mi := &file_types_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandCatalog) ProtoMessage() {}

func (x *CommandCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandCatalog.ProtoReflect.Descriptor instead.
func (*CommandCatalog) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandCatalog) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_types_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_types_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResult) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type CommandReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReceipt) Reset() {
	*x = CommandReceipt{}
	mi := &file_types_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReceipt) ProtoMessage() {}

func (x *CommandReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReceipt.ProtoReflect.Descriptor instead.
func (*CommandReceipt) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{4}
}

func (x *CommandReceipt) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CommandReceipt) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandReceipt) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CommandProtocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*CommandProtocolMessage_Request
	//	*CommandProtocolMessage_Result
	//	*CommandProtocolMessage_Catalog
	//	*CommandProtocolMessage_Receipt
	Message       isCommandProtocolMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandProtocolMessage) Reset() {
	*x = CommandProtocolMessage{}
	mi := &file_types_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandProtocolMessage) ProtoMessage() {}

func (x *CommandProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandProtocolMessage.ProtoReflect.Descriptor instead.
func (*CommandProtocolMessage) Descriptor() ([]byte, []int) {
	return file_types_command_proto_rawDescGZIP(), []int{5}
}

func (x *CommandProtocolMessage) GetMessage() isCommandProtocolMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CommandProtocolMessage) GetRequest() *CommandRequest {
	if x != nil {
		if x, ok := x.Message.(*CommandProtocolMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *CommandProtocolMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*CommandProtocolMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *CommandProtocolMessage) GetCatalog() *CommandCatalog {
	if x != nil {
		if x, ok := x.Message.(*CommandProtocolMessage_Catalog); ok {
			return x.Catalog
		}
	}
	return nil
}

func (x *CommandProtocolMessage) GetReceipt() *CommandReceipt {
	if x != nil {
		if x, ok := x.Message.(*CommandProtocolMessage_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

type isCommandProtocolMessage_Message interface {
	isCommandProtocolMessage_Message()
}

type CommandProtocolMessage_Request struct {
	Request *CommandRequest `protobuf:"bytes,10,opt,name=request,proto3,oneof"`
}

type CommandProtocolMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,11,opt,name=result,proto3,oneof"`
}

type CommandProtocolMessage_Catalog struct {
	Catalog *CommandCatalog `protobuf:"bytes,12,opt,name=catalog,proto3,oneof"`
}

type CommandProtocolMessage_Receipt struct {
	Receipt *CommandReceipt `protobuf:"bytes,13,opt,name=receipt,proto3,oneof"`
}

func (*CommandProtocolMessage_Request) isCommandProtocolMessage_Message() {}

func (*CommandProtocolMessage_Result) isCommandProtocolMessage_Message() {}

func (*CommandProtocolMessage_Catalog) isCommandProtocolMessage_Message() {}

func (*CommandProtocolMessage_Receipt) isCommandProtocolMessage_Message() {}

var File_types_command_proto protoreflect.FileDescriptor

const file_types_command_proto_rawDesc = "" +
	"\n" +
	"\x13types/command.proto\x12\x0eaiscan.command\"s\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"I\n" +
	"\x0eCommandCatalog\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.aiscan.command.CommandSpecR\bcommands\"C\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"B\n" +
	"\rCommandResult\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\"h\n" +
	"\x0eCommandReceipt\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\x90\x02\n" +
	"\x16CommandProtocolMessage\x12:\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x1e.aiscan.command.CommandRequestH\x00R\arequest\x127\n" +
	"\x06result\x18\v \x01(\v2\x1d.aiscan.command.CommandResultH\x00R\x06result\x12:\n" +
	"\acatalog\x18\f \x01(\v2\x1e.aiscan.command.CommandCatalogH\x00R\acatalog\x12:\n" +
	"\areceipt\x18\r \x01(\v2\x1e.aiscan.command.CommandReceiptH\x00R\areceiptB\t\n" +
	"\amessageB1Z/github.com/chainreactors/aiscan/pkg/types;typesb\x06proto3"

var (
	file_types_command_proto_rawDescOnce sync.Once
	file_types_command_proto_rawDescData []byte
)

func file_types_command_proto_rawDescGZIP() []byte {
	file_types_command_proto_rawDescOnce.Do(func() {
		file_types_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_command_proto_rawDesc), len(file_types_command_proto_rawDesc)))
	})
	return file_types_command_proto_rawDescData
}

var file_types_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_command_proto_goTypes = []any{
	(*CommandSpec)(nil),            // 0: aiscan.command.CommandSpec
	(*CommandCatalog)(nil),         // 1: aiscan.command.CommandCatalog
	(*CommandRequest)(nil),         // 2: aiscan.command.CommandRequest
	(*CommandResult)(nil),          // 3: aiscan.command.CommandResult
	(*CommandReceipt)(nil),         // 4: aiscan.command.CommandReceipt
	(*CommandProtocolMessage)(nil), // 5: aiscan.command.CommandProtocolMessage
}
var file_types_command_proto_depIdxs = []int32{
	0, // 0: aiscan.command.CommandCatalog.commands:type_name -> aiscan.command.CommandSpec
	2, // 1: aiscan.command.CommandProtocolMessage.request:type_name -> aiscan.command.CommandRequest
	3, // 2: aiscan.command.CommandProtocolMessage.result:type_name -> aiscan.command.CommandResult
	1, // 3: aiscan.command.CommandProtocolMessage.catalog:type_name -> aiscan.command.CommandCatalog
	4, // 4: aiscan.command.CommandProtocolMessage.receipt:type_name -> aiscan.command.CommandReceipt
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_types_command_proto_init() }
func file_types_command_proto_init() {
	if File_types_command_proto != nil {
		return
	}
	file_types_command_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandProtocolMessage_Request)(nil),
		(*CommandProtocolMessage_Result)(nil),
		(*CommandProtocolMessage_Catalog)(nil),
		(*CommandProtocolMessage_Receipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_command_proto_rawDesc), len(file_types_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_command_proto_goTypes,
		DependencyIndexes: file_types_command_proto_depIdxs,
		MessageInfos:      file_types_command_proto_msgTypes,
	}.Build()
	File_types_command_proto = out.File
	file_types_command_proto_goTypes = nil
	file_types_command_proto_depIdxs = nil
}
