// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v6.33.0
// source: types/config.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Llm      *LLMConfig      `protobuf:"bytes,1,opt,name=llm,proto3" json:"llm,omitempty"`
	Cyberhub *CyberhubConfig `protobuf:"bytes,2,opt,name=cyberhub,proto3" json:"cyberhub,omitempty"`
	Recon    *ReconConfig    `protobuf:"bytes,3,opt,name=recon,proto3" json:"recon,omitempty"`
	Scan     *ScanConfig     `protobuf:"bytes,4,opt,name=scan,proto3" json:"scan,omitempty"`
	Search   *SearchConfig   `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	Ioa      *IOAConfig      `protobuf:"bytes,6,opt,name=ioa,proto3" json:"ioa,omitempty"`
	Agent    *AgentConfig    `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *DistributeConfig) Reset() {
	*x = DistributeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeConfig) ProtoMessage() {}

func (x *DistributeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeConfig.ProtoReflect.Descriptor instead.
func (*DistributeConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{0}
}

func (x *DistributeConfig) GetLlm() *LLMConfig {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *DistributeConfig) GetCyberhub() *CyberhubConfig {
	if x != nil {
		return x.Cyberhub
	}
	return nil
}

func (x *DistributeConfig) GetRecon() *ReconConfig {
	if x != nil {
		return x.Recon
	}
	return nil
}

func (x *DistributeConfig) GetScan() *ScanConfig {
	if x != nil {
		return x.Scan
	}
	return nil
}

func (x *DistributeConfig) GetSearch() *SearchConfig {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *DistributeConfig) GetIoa() *IOAConfig {
	if x != nil {
		return x.Ioa
	}
	return nil
}

func (x *DistributeConfig) GetAgent() *AgentConfig {
	if x != nil {
		return x.Agent
	}
	return nil
}

type LLMConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveProfile string               `protobuf:"bytes,1,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	Providers     []*LLMProviderConfig `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *LLMConfig) Reset() {
	*x = LLMConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMConfig) ProtoMessage() {}

func (x *LLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMConfig.ProtoReflect.Descriptor instead.
func (*LLMConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{1}
}

func (x *LLMConfig) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *LLMConfig) GetProviders() []*LLMProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

type LLMProviderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Proxy         string `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	MaxTokens     int32  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow int32  `protobuf:"varint,9,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
}

func (x *LLMProviderConfig) Reset() {
	*x = LLMProviderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderConfig) ProtoMessage() {}

func (x *LLMProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderConfig.ProtoReflect.Descriptor instead.
func (*LLMProviderConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{2}
}

func (x *LLMProviderConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMProviderConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMProviderConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMProviderConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProviderConfig) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *LLMProviderConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMProviderConfig) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type CyberhubConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Mode  string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Proxy string `protobuf:"bytes,4,opt,name=proxy,proto3" json:"proxy,omitempty"`
}

func (x *CyberhubConfig) Reset() {
	*x = CyberhubConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CyberhubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CyberhubConfig) ProtoMessage() {}

func (x *CyberhubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CyberhubConfig.ProtoReflect.Descriptor instead.
func (*CyberhubConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{3}
}

func (x *CyberhubConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CyberhubConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CyberhubConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CyberhubConfig) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type ReconConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FofaEmail    string `protobuf:"bytes,1,opt,name=fofa_email,json=fofaEmail,proto3" json:"fofa_email,omitempty"`
	FofaKey      string `protobuf:"bytes,2,opt,name=fofa_key,json=fofaKey,proto3" json:"fofa_key,omitempty"`
	HunterToken  string `protobuf:"bytes,3,opt,name=hunter_token,json=hunterToken,proto3" json:"hunter_token,omitempty"`
	HunterApiKey string `protobuf:"bytes,4,opt,name=hunter_api_key,json=hunterApiKey,proto3" json:"hunter_api_key,omitempty"`
	Proxy        string `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Limit        int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ReconConfig) Reset() {
	*x = ReconConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconConfig) ProtoMessage() {}

func (x *ReconConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconConfig.ProtoReflect.Descriptor instead.
func (*ReconConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{4}
}

func (x *ReconConfig) GetFofaEmail() string {
	if x != nil {
		return x.FofaEmail
	}
	return ""
}

func (x *ReconConfig) GetFofaKey() string {
	if x != nil {
		return x.FofaKey
	}
	return ""
}

func (x *ReconConfig) GetHunterToken() string {
	if x != nil {
		return x.HunterToken
	}
	return ""
}

func (x *ReconConfig) GetHunterApiKey() string {
	if x != nil {
		return x.HunterApiKey
	}
	return ""
}

func (x *ReconConfig) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *ReconConfig) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScanConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verify string `protobuf:"bytes,1,opt,name=verify,proto3" json:"verify,omitempty"`
}

func (x *ScanConfig) Reset() {
	*x = ScanConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanConfig) ProtoMessage() {}

func (x *ScanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanConfig.ProtoReflect.Descriptor instead.
func (*ScanConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{5}
}

func (x *ScanConfig) GetVerify() string {
	if x != nil {
		return x.Verify
	}
	return ""
}

type SearchConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TavilyKeys string `protobuf:"bytes,1,opt,name=tavily_keys,json=tavilyKeys,proto3" json:"tavily_keys,omitempty"`
}

func (x *SearchConfig) Reset() {
	*x = SearchConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConfig) ProtoMessage() {}

func (x *SearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConfig.ProtoReflect.Descriptor instead.
func (*SearchConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{6}
}

func (x *SearchConfig) GetTavilyKeys() string {
	if x != nil {
		return x.TavilyKeys
	}
	return ""
}

type IOAConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NodeName string `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Space    string `protobuf:"bytes,4,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *IOAConfig) Reset() {
	*x = IOAConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOAConfig) ProtoMessage() {}

func (x *IOAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOAConfig.ProtoReflect.Descriptor instead.
func (*IOAConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{7}
}

func (x *IOAConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IOAConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IOAConfig) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *IOAConfig) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

type AgentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tools       []string `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	Timeout     int32    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	SaveSession bool     `protobuf:"varint,3,opt,name=save_session,json=saveSession,proto3" json:"save_session,omitempty"`
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{8}
}

func (x *AgentConfig) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *AgentConfig) GetSaveSession() bool {
	if x != nil {
		return x.SaveSession
	}
	return false
}

type LLMProviderView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider         string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl          string `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKeyConfigured bool   `protobuf:"varint,5,opt,name=api_key_configured,json=apiKeyConfigured,proto3" json:"api_key_configured,omitempty"`
	Model            string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Proxy            string `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	MaxTokens        int32  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ContextWindow    int32  `protobuf:"varint,9,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
}

func (x *LLMProviderView) Reset() {
	*x = LLMProviderView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMProviderView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderView) ProtoMessage() {}

func (x *LLMProviderView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderView.ProtoReflect.Descriptor instead.
func (*LLMProviderView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{9}
}

func (x *LLMProviderView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMProviderView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMProviderView) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProviderView) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProviderView) GetApiKeyConfigured() bool {
	if x != nil {
		return x.ApiKeyConfigured
	}
	return false
}

func (x *LLMProviderView) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProviderView) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *LLMProviderView) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMProviderView) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type LLMView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveProfile string             `protobuf:"bytes,1,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	Active        *LLMProviderView   `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	Providers     []*LLMProviderView `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *LLMView) Reset() {
	*x = LLMView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMView) ProtoMessage() {}

func (x *LLMView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMView.ProtoReflect.Descriptor instead.
func (*LLMView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{10}
}

func (x *LLMView) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *LLMView) GetActive() *LLMProviderView {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *LLMView) GetProviders() []*LLMProviderView {
	if x != nil {
		return x.Providers
	}
	return nil
}

type CyberhubView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	KeyConfigured bool   `protobuf:"varint,2,opt,name=key_configured,json=keyConfigured,proto3" json:"key_configured,omitempty"`
	Mode          string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Proxy         string `protobuf:"bytes,4,opt,name=proxy,proto3" json:"proxy,omitempty"`
}

func (x *CyberhubView) Reset() {
	*x = CyberhubView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CyberhubView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CyberhubView) ProtoMessage() {}

func (x *CyberhubView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CyberhubView.ProtoReflect.Descriptor instead.
func (*CyberhubView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{11}
}

func (x *CyberhubView) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CyberhubView) GetKeyConfigured() bool {
	if x != nil {
		return x.KeyConfigured
	}
	return false
}

func (x *CyberhubView) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CyberhubView) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type ReconView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FofaEmail              string `protobuf:"bytes,1,opt,name=fofa_email,json=fofaEmail,proto3" json:"fofa_email,omitempty"`
	FofaKeyConfigured      bool   `protobuf:"varint,2,opt,name=fofa_key_configured,json=fofaKeyConfigured,proto3" json:"fofa_key_configured,omitempty"`
	HunterTokenConfigured  bool   `protobuf:"varint,3,opt,name=hunter_token_configured,json=hunterTokenConfigured,proto3" json:"hunter_token_configured,omitempty"`
	HunterApiKeyConfigured bool   `protobuf:"varint,4,opt,name=hunter_api_key_configured,json=hunterApiKeyConfigured,proto3" json:"hunter_api_key_configured,omitempty"`
	Proxy                  string `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Limit                  int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ReconView) Reset() {
	*x = ReconView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconView) ProtoMessage() {}

func (x *ReconView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconView.ProtoReflect.Descriptor instead.
func (*ReconView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{12}
}

func (x *ReconView) GetFofaEmail() string {
	if x != nil {
		return x.FofaEmail
	}
	return ""
}

func (x *ReconView) GetFofaKeyConfigured() bool {
	if x != nil {
		return x.FofaKeyConfigured
	}
	return false
}

func (x *ReconView) GetHunterTokenConfigured() bool {
	if x != nil {
		return x.HunterTokenConfigured
	}
	return false
}

func (x *ReconView) GetHunterApiKeyConfigured() bool {
	if x != nil {
		return x.HunterApiKeyConfigured
	}
	return false
}

func (x *ReconView) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *ReconView) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TavilyKeysConfigured bool `protobuf:"varint,1,opt,name=tavily_keys_configured,json=tavilyKeysConfigured,proto3" json:"tavily_keys_configured,omitempty"`
}

func (x *SearchView) Reset() {
	*x = SearchView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchView) ProtoMessage() {}

func (x *SearchView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchView.ProtoReflect.Descriptor instead.
func (*SearchView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{13}
}

func (x *SearchView) GetTavilyKeysConfigured() bool {
	if x != nil {
		return x.TavilyKeysConfigured
	}
	return false
}

type IOAView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url             string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TokenConfigured bool   `protobuf:"varint,2,opt,name=token_configured,json=tokenConfigured,proto3" json:"token_configured,omitempty"`
	NodeName        string `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Space           string `protobuf:"bytes,4,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *IOAView) Reset() {
	*x = IOAView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOAView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOAView) ProtoMessage() {}

func (x *IOAView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOAView.ProtoReflect.Descriptor instead.
func (*IOAView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{14}
}

func (x *IOAView) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IOAView) GetTokenConfigured() bool {
	if x != nil {
		return x.TokenConfigured
	}
	return false
}

func (x *IOAView) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *IOAView) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

type ConfigView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string        `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Loaded   bool          `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Llm      *LLMView      `protobuf:"bytes,3,opt,name=llm,proto3" json:"llm,omitempty"`
	Cyberhub *CyberhubView `protobuf:"bytes,4,opt,name=cyberhub,proto3" json:"cyberhub,omitempty"`
	Recon    *ReconView    `protobuf:"bytes,5,opt,name=recon,proto3" json:"recon,omitempty"`
	Scan     *ScanConfig   `protobuf:"bytes,6,opt,name=scan,proto3" json:"scan,omitempty"`
	Search   *SearchView   `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	Ioa      *IOAView      `protobuf:"bytes,8,opt,name=ioa,proto3" json:"ioa,omitempty"`
	Agent    *AgentConfig  `protobuf:"bytes,9,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *ConfigView) Reset() {
	*x = ConfigView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigView) ProtoMessage() {}

func (x *ConfigView) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigView.ProtoReflect.Descriptor instead.
func (*ConfigView) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigView) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigView) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ConfigView) GetLlm() *LLMView {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *ConfigView) GetCyberhub() *CyberhubView {
	if x != nil {
		return x.Cyberhub
	}
	return nil
}

func (x *ConfigView) GetRecon() *ReconView {
	if x != nil {
		return x.Recon
	}
	return nil
}

func (x *ConfigView) GetScan() *ScanConfig {
	if x != nil {
		return x.Scan
	}
	return nil
}

func (x *ConfigView) GetSearch() *SearchView {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ConfigView) GetIoa() *IOAView {
	if x != nil {
		return x.Ioa
	}
	return nil
}

func (x *ConfigView) GetAgent() *AgentConfig {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigView `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{16}
}

func (x *GetConfigResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *DistributeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateConfigRequest) GetConfig() *DistributeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigView `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateConfigResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type ActivateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
}

func (x *ActivateProfileRequest) Reset() {
	*x = ActivateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileRequest) ProtoMessage() {}

func (x *ActivateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileRequest.ProtoReflect.Descriptor instead.
func (*ActivateProfileRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{19}
}

func (x *ActivateProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ActivateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigView `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ActivateProfileResponse) Reset() {
	*x = ActivateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileResponse) ProtoMessage() {}

func (x *ActivateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileResponse.ProtoReflect.Descriptor instead.
func (*ActivateProfileResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{20}
}

func (x *ActivateProfileResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type LLMProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Provider  string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl   string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey    string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model     string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Proxy     string `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
}

func (x *LLMProbeRequest) Reset() {
	*x = LLMProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProbeRequest) ProtoMessage() {}

func (x *LLMProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProbeRequest.ProtoReflect.Descriptor instead.
func (*LLMProbeRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{21}
}

func (x *LLMProbeRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *LLMProbeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProbeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMProbeRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMProbeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProbeRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type LLMProbeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Provider  string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Model     string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs int64  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Reply     string `protobuf:"bytes,5,opt,name=reply,proto3" json:"reply,omitempty"`
	Error     string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LLMProbeResult) Reset() {
	*x = LLMProbeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProbeResult) ProtoMessage() {}

func (x *LLMProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProbeResult.ProtoReflect.Descriptor instead.
func (*LLMProbeResult) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{22}
}

func (x *LLMProbeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LLMProbeResult) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProbeResult) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMProbeResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LLMProbeResult) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *LLMProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListModelsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Supported bool     `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	Models    []string `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Error     string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListModelsResult) Reset() {
	*x = ListModelsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModelsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResult) ProtoMessage() {}

func (x *ListModelsResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResult.ProtoReflect.Descriptor instead.
func (*ListModelsResult) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{23}
}

func (x *ListModelsResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListModelsResult) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *ListModelsResult) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section string            `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Config  *DistributeConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{24}
}

func (x *TestConnectionRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *TestConnectionRequest) GetConfig() *DistributeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConnectionCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok        bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	LatencyMs int64  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Detail    string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Error     string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConnectionCheck) Reset() {
	*x = ConnectionCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionCheck) ProtoMessage() {}

func (x *ConnectionCheck) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionCheck.ProtoReflect.Descriptor instead.
func (*ConnectionCheck) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{25}
}

func (x *ConnectionCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionCheck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectionCheck) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ConnectionCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ConnectionCheck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checks []*ConnectionCheck `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_config_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_config_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_types_config_proto_rawDescGZIP(), []int{26}
}

func (x *TestConnectionResponse) GetChecks() []*ConnectionCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_types_config_proto protoreflect.FileDescriptor

var file_types_config_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0xed, 0x02, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2a, 0x0a, 0x03, 0x6c, 0x6c, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4c, 0x4c, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x03, 0x6c, 0x6c, 0x6d, 0x12, 0x39, 0x0a, 0x08, 0x63, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x63, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x12,
	0x30, 0x0a, 0x05, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x72, 0x65, 0x63, 0x6f,
	0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x73, 0x63, 0x61, 0x6e,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x2a, 0x0a, 0x03, 0x69, 0x6f, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x49, 0x4f, 0x41, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x69, 0x6f,
	0x61, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x22, 0x72, 0x0a, 0x09, 0x4c, 0x4c, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x69, 0x73,
	0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4c, 0x4c, 0x4d, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x11, 0x4c, 0x4c, 0x4d, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x22, 0x5e, 0x0a, 0x0e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x66, 0x61, 0x5f, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x66, 0x61, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6f, 0x66, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f, 0x66, 0x61, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a,
	0x0c, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x24, 0x0a, 0x0e, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x2f, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x76, 0x69,
	0x6c, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x61, 0x76, 0x69, 0x6c, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x66, 0x0a, 0x09, 0x49, 0x4f, 0x41,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x60, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x61, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x02, 0x0a, 0x0f, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x22, 0xa6, 0x01, 0x0a, 0x07, 0x4c, 0x4c, 0x4d, 0x56, 0x69, 0x65, 0x77, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x3c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x22, 0x71, 0x0a, 0x0c, 0x43,
	0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x56, 0x69, 0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x25, 0x0a,
	0x0e, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0xf9,
	0x01, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x6f, 0x66, 0x61, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x6f, 0x66, 0x61, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2e, 0x0a, 0x13, 0x66,
	0x6f, 0x66, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x66, 0x6f, 0x66, 0x61, 0x4b, 0x65,
	0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x68,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x68, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x19, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x68, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x65, 0x77, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x61, 0x76, 0x69,
	0x6c, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x74, 0x61, 0x76, 0x69, 0x6c, 0x79,
	0x4b, 0x65, 0x79, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x22, 0x79,
	0x0a, 0x07, 0x49, 0x4f, 0x41, 0x56, 0x69, 0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x29, 0x0a, 0x10, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x89, 0x03, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x03, 0x6c, 0x6c, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x4c, 0x4c, 0x4d, 0x56, 0x69, 0x65, 0x77, 0x52, 0x03, 0x6c, 0x6c, 0x6d, 0x12, 0x37,
	0x0a, 0x08, 0x63, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x43, 0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x56, 0x69, 0x65, 0x77, 0x52, 0x08, 0x63,
	0x79, 0x62, 0x65, 0x72, 0x68, 0x75, 0x62, 0x12, 0x2e, 0x0a, 0x05, 0x72, 0x65, 0x63, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x05, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x69, 0x65,
	0x77, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x03, 0x69, 0x6f, 0x61,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x49, 0x4f, 0x41, 0x56, 0x69, 0x65, 0x77, 0x52, 0x03,
	0x69, 0x6f, 0x61, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x69, 0x73,
	0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x56, 0x69, 0x65, 0x77, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x4e, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x49, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x37, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x4c, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x56, 0x69, 0x65, 0x77, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0xac, 0x01, 0x0a, 0x0f, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x9d,
	0x01, 0x0a, 0x0e, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6e,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6a,
	0x0a, 0x15, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x69, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x50, 0x0a, 0x16, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x69, 0x73, 0x63,
	0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x61, 0x69,
	0x73, 0x63, 0x61, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_config_proto_rawDescOnce sync.Once
	file_types_config_proto_rawDescData = file_types_config_proto_rawDesc
)

func file_types_config_proto_rawDescGZIP() []byte {
	file_types_config_proto_rawDescOnce.Do(func() {
		file_types_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_config_proto_rawDescData)
	})
	return file_types_config_proto_rawDescData
}

var file_types_config_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_types_config_proto_goTypes = []interface{}{
	(*DistributeConfig)(nil),        // 0: aiscan.config.DistributeConfig
	(*LLMConfig)(nil),               // 1: aiscan.config.LLMConfig
	(*LLMProviderConfig)(nil),       // 2: aiscan.config.LLMProviderConfig
	(*CyberhubConfig)(nil),          // 3: aiscan.config.CyberhubConfig
	(*ReconConfig)(nil),             // 4: aiscan.config.ReconConfig
	(*ScanConfig)(nil),              // 5: aiscan.config.ScanConfig
	(*SearchConfig)(nil),            // 6: aiscan.config.SearchConfig
	(*IOAConfig)(nil),               // 7: aiscan.config.IOAConfig
	(*AgentConfig)(nil),             // 8: aiscan.config.AgentConfig
	(*LLMProviderView)(nil),         // 9: aiscan.config.LLMProviderView
	(*LLMView)(nil),                 // 10: aiscan.config.LLMView
	(*CyberhubView)(nil),            // 11: aiscan.config.CyberhubView
	(*ReconView)(nil),               // 12: aiscan.config.ReconView
	(*SearchView)(nil),              // 13: aiscan.config.SearchView
	(*IOAView)(nil),                 // 14: aiscan.config.IOAView
	(*ConfigView)(nil),              // 15: aiscan.config.ConfigView
	(*GetConfigResponse)(nil),       // 16: aiscan.config.GetConfigResponse
	(*UpdateConfigRequest)(nil),     // 17: aiscan.config.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),    // 18: aiscan.config.UpdateConfigResponse
	(*ActivateProfileRequest)(nil),  // 19: aiscan.config.ActivateProfileRequest
	(*ActivateProfileResponse)(nil), // 20: aiscan.config.ActivateProfileResponse
	(*LLMProbeRequest)(nil),         // 21: aiscan.config.LLMProbeRequest
	(*LLMProbeResult)(nil),          // 22: aiscan.config.LLMProbeResult
	(*ListModelsResult)(nil),        // 23: aiscan.config.ListModelsResult
	(*TestConnectionRequest)(nil),   // 24: aiscan.config.TestConnectionRequest
	(*ConnectionCheck)(nil),         // 25: aiscan.config.ConnectionCheck
	(*TestConnectionResponse)(nil),  // 26: aiscan.config.TestConnectionResponse
}
var file_types_config_proto_depIdxs = []int32{
	1,  // 0: aiscan.config.DistributeConfig.llm:type_name -> aiscan.config.LLMConfig
	3,  // 1: aiscan.config.DistributeConfig.cyberhub:type_name -> aiscan.config.CyberhubConfig
	4,  // 2: aiscan.config.DistributeConfig.recon:type_name -> aiscan.config.ReconConfig
	5,  // 3: aiscan.config.DistributeConfig.scan:type_name -> aiscan.config.ScanConfig
	6,  // 4: aiscan.config.DistributeConfig.search:type_name -> aiscan.config.SearchConfig
	7,  // 5: aiscan.config.DistributeConfig.ioa:type_name -> aiscan.config.IOAConfig
	8,  // 6: aiscan.config.DistributeConfig.agent:type_name -> aiscan.config.AgentConfig
	2,  // 7: aiscan.config.LLMConfig.providers:type_name -> aiscan.config.LLMProviderConfig
	9,  // 8: aiscan.config.LLMView.active:type_name -> aiscan.config.LLMProviderView
	9,  // 9: aiscan.config.LLMView.providers:type_name -> aiscan.config.LLMProviderView
	10, // 10: aiscan.config.ConfigView.llm:type_name -> aiscan.config.LLMView
	11, // 11: aiscan.config.ConfigView.cyberhub:type_name -> aiscan.config.CyberhubView
	12, // 12: aiscan.config.ConfigView.recon:type_name -> aiscan.config.ReconView
	5,  // 13: aiscan.config.ConfigView.scan:type_name -> aiscan.config.ScanConfig
	13, // 14: aiscan.config.ConfigView.search:type_name -> aiscan.config.SearchView
	14, // 15: aiscan.config.ConfigView.ioa:type_name -> aiscan.config.IOAView
	8,  // 16: aiscan.config.ConfigView.agent:type_name -> aiscan.config.AgentConfig
	15, // 17: aiscan.config.GetConfigResponse.config:type_name -> aiscan.config.ConfigView
	0,  // 18: aiscan.config.UpdateConfigRequest.config:type_name -> aiscan.config.DistributeConfig
	15, // 19: aiscan.config.UpdateConfigResponse.config:type_name -> aiscan.config.ConfigView
	15, // 20: aiscan.config.ActivateProfileResponse.config:type_name -> aiscan.config.ConfigView
	0,  // 21: aiscan.config.TestConnectionRequest.config:type_name -> aiscan.config.DistributeConfig
	25, // 22: aiscan.config.TestConnectionResponse.checks:type_name -> aiscan.config.ConnectionCheck
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_types_config_proto_init() }
func file_types_config_proto_init() {
	if File_types_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMProviderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CyberhubConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOAConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMProviderView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CyberhubView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOAView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMProbeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListModelsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_config_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_config_proto_goTypes,
		DependencyIndexes: file_types_config_proto_depIdxs,
		MessageInfos:      file_types_config_proto_msgTypes,
	}.Build()
	File_types_config_proto = out.File
	file_types_config_proto_rawDesc = nil
	file_types_config_proto_goTypes = nil
	file_types_config_proto_depIdxs = nil
}
