syntax = "proto3";

package cyber.rpc.chat;

import "aop/chat.proto";
import "types/chat.proto";

option go_package = "github.com/chainreactors/cyber/pkg/rpc;rpc";

service SessionService {
  rpc UpdateSession(cyber.chat.UpdateSessionRequest) returns (cyber.chat.UpdateSessionResponse);
  rpc ListSessions(cyber.chat.ListSessionsRequest) returns (cyber.chat.ListSessionsResponse);
  rpc GetSession(cyber.chat.GetSessionRequest) returns (cyber.chat.GetSessionResponse);
  rpc ResetSession(cyber.chat.ResetSessionRequest) returns (cyber.chat.ResetSessionResponse);
  rpc DeleteSession(cyber.chat.DeleteSessionRequest) returns (cyber.chat.DeleteSessionResponse);
  rpc ListCommands(cyber.chat.ListCommandsRequest) returns (cyber.chat.ListCommandsResponse);
  rpc ListEvents(aop.ListEventsRequest) returns (aop.ListEventsResponse);
}
