syntax = "proto3";

package cyber.rpc.sco;

import "types/sco.proto";

option go_package = "github.com/chainreactors/cyber/pkg/rpc;rpc";

service SCOService {
  rpc ListNodes(cyber.sco.ListNodesRequest) returns (cyber.sco.ListNodesResponse);
  rpc GetNode(cyber.sco.GetNodeRequest) returns (cyber.sco.GetNodeResponse);
  rpc GetStats(cyber.sco.GetStatsRequest) returns (cyber.sco.GetStatsResponse);
  rpc DeleteNodes(cyber.sco.DeleteNodesRequest) returns (cyber.sco.DeleteNodesResponse);
  rpc ImportNodes(cyber.sco.ImportNodesRequest) returns (cyber.sco.ImportNodesResponse);
  rpc ListArtifacts(cyber.sco.ListArtifactsRequest) returns (cyber.sco.ListArtifactsResponse);
}
